<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Ransomware</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Management" />
    <Reference Include="System.Core">
      <HintPath>../../dotnet/shared/Microsoft.NETCore.App/8.0.15/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceProcess">
      <HintPath>../../dotnet/shared/Microsoft.NETCore.App/8.0.15/System.ServiceProcess.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>