<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>shade</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>Exe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net481</TargetFramework>
    <Prefer32Bit>True</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="System.Core">
      <HintPath>../../dotnet/shared/Microsoft.NETCore.App/8.0.15/System.Core.dll</HintPath>
    </Reference>
    <Reference Include="Microsoft.VisualBasic" />
  </ItemGroup>
</Project>